mattermost/mattermost-developer-documentation

site/config.toml

Syntax highlighting just isn't enabled by default for markdown (https://gohugo.io/content-management/syntax-highlighting/#highlight-in-code-fences).
🎉  http://mattermost-developer-documentation.s3-website-us-east-1.amazonaws.com/branches/syntax-highlighting/extend/server/hello-world/
Closes #13

pygmentsCodefences=true

---

.gitignore
.travis.yml
Makefile
scripts/plugin-godocs.go
site/content/extend/server/api-reference.md
site/content/extend/server/hello-world.md
site/content/extend/server/reference.md
site/layouts/shortcodes/plugingodocs.html
site/layouts/shortcodes/plugingoexamplecode.html

Make target `go get`s the plugin package and runs a script to generate a JSON representation of the documentation. That JSON is put into the site/data directory, and is used by a layout to generate the HTML for the API reference:
http://mattermost-developer-documentation.s3-website-us-east-1.amazonaws.com/branches/add-server-api-reference/extend/server/reference/
If you just use `hugo server` without generating the docs, that page will just have some placeholder text telling you what to do.
It's just a start, but it's already more usable than GoDoc for this since GoDoc completely neglects documentation for interface methods. In addition to styling and more detailed docs, I'll definitely want an "introduced in version 4.X" tag on each method.
Also updated the Travis settings to build …

Add server api reference

---

.gitignore
Makefile
scripts/plugin-godocs.go
scripts/plugin-manifest-docs.go
site/content/extend/example-plugins.md
site/content/extend/manifest-reference.md
site/content/extend/server/_index.md
site/content/extend/webapp/_index.md
site/layouts/shortcodes/plugingodocs.html
site/layouts/shortcodes/pluginmanifestdocs.html

http://mattermost-developer-documentation.s3-website-us-east-1.amazonaws.com/branches/manifest-reference/extend/manifest-reference/
It's more useful with actual documentation (see https://github.com/mattermost/mattermost-server/pull/7806). Also needs styling. But it gets the important stuff there:

Add plugin manifest reference

---

site/config.toml
site/layouts/index.html
site/layouts/partials/head.html
site/layouts/partials/homehead.html
site/static/css/markdown.css

* Stopped using the theme's style for the doc and blog pages, and added some markdown table styling
* Changed the code theme to manni because the default was expecting a dark background
The doc pages are much easier on the eyes now until we get a real designer to help (coming soon)

Some styling updates

---

site/config.toml
site/content/blog/repo-split.md
site/content/blog/welcome.md
site/content/contribute/_index.md
site/content/contribute/getting-started/_index.md
site/content/contribute/getting-started/contribution-guidelines.md
site/content/contribute/getting-started/core-developers.md
site/content/contribute/getting-started/respositories.md
site/content/contribute/mobile/_index.md
site/content/contribute/mobile/developer-setup.md
site/content/contribute/redux/_index.md
site/content/contribute/redux/actions.md
site/content/contribute/redux/developer-setup.md
site/content/contribute/redux/developer-workflow.md
site/content/contribute/redux/selectors.md
site/content/contribute/server/_index.md
site/content/contribute/server/developer-setup.md
site/content/contribute/server/developer-workflow.md
site/content/contribute/server/rest-api.md
site/content/contribute/webapp/_index.md
site/content/contribute/webapp/developer-setup.md
site/content/extend/plugins/example-plugins.md
site/content/integrate/_index.md
site/layouts/partials/intro.html
site/layouts/partials/mailinglist.html
site/layouts/partials/nav.html
site/layouts/partials/nav2.html

* Mark everything but plugin and internal as drafts
* Update navbar to use drafts as well and hide contribute, extend, blog under drafts
* Update homepage to show "Coming Soon" for contribute and integrate sections when not in draft mode
* Disable mailing list until marketing is consulted (might want to switch to mailchimp)

Make use of drafts

---

.travis.yml

This deploys all commits to S3. Each commit deployed to S3 now gets a commit status where the details link takes you to the actual deployment. So instead of URL hacking when looking at your PRs, I can just click that. And I can go back in time and view past commits.
I've also added a lifecycle policy to the S3 bucket to move builds to infrequent access after 30 days and save us a few pennies.
Closes #28

Add after_deploy status, archive all commits

---

site/content/internal/infrastructure/build.md

Primarily to get the Go upgrade process down in writing.
http://mattermost-developer-documentation.s3-website-us-east-1.amazonaws.com/branches/build-infra-docs/internal/infrastructure/build/

Add build infrastructure docs

---

site/content/extend/plugins/manifest-reference.md
site/layouts/shortcodes/pluginmanifestdocs.html

* Adds "Manifest Reference" header.
* Moves top-level manifest documentation above the ToC.
* Makes the ToC and Documentation headers one level smaller.
Closes #52

Manifest reference style update

---

site/content/contribute/getting-started/core-committers.md

Mainly just switching "core developers" to "core committers" to be in line with our other documentation and adding Martin.

Update the core committers page

---

site/content/contribute/_index.md
site/content/contribute/getting-started/contribution-guidelines.md
site/static/css/styles.css

Also removed empty page + minor update to paragraph spacing.

Update contribution guidelines

---

site/content/contribute/desktop/code-signing.md

Clarified that code signing will automatically be performed as a part of the build on macOS if certs and keys are installed

Clarification of Code Signing Steps on macOS

---

site/content/contribute/desktop/code-signing.md

Added work-around steps for issues encountered when code signing macOS builds via SSH

More macOS Code Signing Tweaks

---

site/content/contribute/desktop/code-signing.md

Added documentation for avoiding a bus error when codesigning Windows executables on Linux systems

Bus Error Avoidance Documentation

---

site/content/integrate/getting-started/_index.md
site/content/integrate/getting-started/how-should-i-integrate.md
site/layouts/shortcodes/bignumber.html
site/static/css/styles.css

Based off #89, so please only review the last commit
The two new pages can be seen here:
* http://mattermost-developer-documentation.s3-website-us-east-1.amazonaws.com/branches/integrate/integrate/getting-started/
* http://mattermost-developer-documentation.s3-website-us-east-1.amazonaws.com/branches/integrate/integrate/getting-started/how-should-i-integrate/
Note that some of the links are pointing to non-existent pages still

 Add getting started section for integrations

---

site/content/integrate/incoming-webhooks/_index.md
site/content/integrate/outgoing-webhooks/_index.md

Also added the `props` parameter to the incoming webhook doc.
Page viewable here: http://mattermost-developer-documentation.s3-website-us-east-1.amazonaws.com/branches/outgoing-webhooks/integrate/outgoing-webhooks/

Add basic outgoing webhook documentation

---

site/content/integrate/getting-started/how-should-i-integrate.md
site/content/integrate/rest-api/_index.md

Originally I was going to write some more documentation and move some of it from api.mattermost.com but I couldn't think of a good way to divide the documentation between the reference and here. It didn't feel right to split it up into two places, and the API reference is already developer focused. So instead, I've opted to just redirect to api.mattermost.com
If someone has a better idea on how to organize the documentation for the API, I'm all ears
I used a redirect purposefully, so we can use links to the dev docs site in case we ever don't want it to redirect and have something different here

MM-10084 Add API reference section that redirects to api.mattermost.com

---

site/content/blog/npm-v6.md

This is a <5 minute effort to replicate a recent announcement on pre-release for future consumption by our developer community.
The blog itself is not yet linked publicly, but can be accessed https://developers.mattermost.com/blog/. It's in need of some styling love, but it seems prudent to start writing "back articles" anyway.

add blog entry for upgrading to npm-v6

---

site/content/contribute/getting-started/_index.md

**Current:**
Select a ticket section with GitHub issues link incorrectly links to https://developers.mattermost.com/contribute/getting-started/(https://github.com/mattermost/mattermost-server/issues?q=is%3Aissue+is%3Aopen+label%3A%22Up+For+Grabs%22)
**Expected:**
Select a ticket section with GitHub issues should link to Mattermost issues that are Up For Grabs https://github.com/mattermost/mattermost-server/issues?q=is:issue+is:open+label:%22Up+For+Grabs%22

Fixing redirect to MM issues on GitHub

---

site/content/contribute/server/developer-setup.md

Fix missing `dockerhost` documentation for OSX:
Fix visual style for corresponding block in Arch:

fix dockerhost mentions

---

site/content/contribute/mobile/developer-setup.md

Ensure `$ANDROID_HOME/emulator` is added to the `$PATH`, as the avd files are relative to the binary and the binary location seems to have [changed](https://stackoverflow.com/questions/26483370/android-emulator-error-message-panic-missing-emulator-engine-program-for-x86).
Also simplify the export to use `$HOME` directly.

fix emulator path

---

site/content/contribute/server/plugins.md

Wanted to get us started on contribution docs for plugins.

Add short plugin overview and steps to add an API to contribution docs

---

site/content/contribute/server/developer-setup.md

As discussed on Pre-Release, this PR adds an explanation how to check if the server is successfully running, and adds a notice that by default there will be a 404 Not Found error if the web app developer setup is not executed.

Add Explanation for 404 and reference to Webapp Setup

---

.travis.yml
site/content/extend/plugins/migration.md

This accompanies the [server changes](https://github.com/mattermost/mattermost-server/pull/9519) to remove support for automatically unmarshalling a plugin's server configuration.
See also
* https://github.com/mattermost/mattermost-plugin-sample/pull/12
* https://github.com/mattermost/mattermost-plugin-demo/pull/7

document migration through removal of auto-unmarshalling

---

site/content/contribute/webapp/webapp-to-redux.md

As I was working on a Redux migration ticket, I copy-pasted a bit of the code in the guide only to realize it had a typo in it (javascript error was quick to show me what was wrong).
Thought I'd patch it up before anyone else ran into the same slight issue

Fixing typo in redux migration guide (fron --> from)

---

scripts/plugin-jsdocs.js

Don't really know why the failure is pointing at my commit but it seems that somehow `statement.loadingComments` is undefined or null and thus causing a crash when running the script, this PR makes it so it does not crash.

Fix crash when running plugin-jsdocs.js

---

site/content/contribute/server/developer-workflow.md
site/content/contribute/webapp/developer-workflow.md

Currently, in the [Server](https://developers.mattermost.com/contribute/server/developer-workflow/) and [Web App](https://developers.mattermost.com/contribute/webapp/developer-workflow/) "Workflow" guides, there is copy to "set up your developer environment" which links to https://docs.mattermost.com/developer/dev-setup.html, which subsequently links the user back to the previous guide in the respective track ("Developer Setup"). This changes the markdown to link directly to the previous "Developer Setup" guide.

link directly to the developer setup guide

---

site/content/contribute/server/developer-setup.md

**Summary**
curl with https ran into SSL_ERROR_RX_RECORD_TOO_LONG error.
**Ticket Link**
N/A - contributing w/o ticket as this is a tiny change
**Checklist**

developer-setup: fixed formating and ping one-liner (to http w/o ssl)

---

site/layouts/_default/list.html
site/layouts/_default/single.html
site/layouts/blog/single.html
site/layouts/partials/hanchor.html
site/static/css/styles.css

Pretty much taken from https://discourse.gohugo.io/t/adding-anchor-next-to-headers/1726/14
Screenshot:
Fixes #60

Add heading anchor

---

site/config.toml
site/layouts/_default/list.html
site/layouts/_default/single.html
site/layouts/partials/hanchor.html
site/layouts/partials/page-edit.html

We could also add some kind of icon. But I don't have one. 
With the current code architecture its quite hard to align the link with the title. If this is wanted, I have to do some larger code changes.
Screenshot:
Fixes #25

Add edit link to pages

---

site/layouts/partials/nav.html
site/layouts/partials/notification.html
site/static/css/bar.css
site/static/css/styles.css
site/static/js/main.js

|  After |  Before |
|---|---|
| ![screenshot from 2018-11-28 16-14-45](https://user-images.githubusercontent.com/16541325/49161247-c25e4700-f328-11e8-991c-532ab8f0642e.png)  |  ![screenshot from 2018-12-04 09-15-10](https://user-images.githubusercontent.com/16541325/49428000-26f42880-f7a5-11e8-9999-7bf1b0cc1dda.png)  |
There a slight changes to the background. I'm not an CSS expert. For comparison  with a closed notification:
|  After |  Before |
|---|---|
| ![screenshot from 2018-11-28 16-11-13](https://user-images.githubusercontent.com/16541325/49161311-e3bf3300-f328-11e8-8fc3-2081d483d2de.png) | ![screenshot from 2018-11-28 16-11-18](https://user-images.githubusercontent.com/16541325/49161325-ea4daa80-f328-11e8-91cd-33ad6d968fee.png) | 
Fixes #5

Improve Notification Bar

---

site/content/integrate/slash-commands/_index.md

@mickmaster Let me know if there is additional information that would be helpful to add for developers.
For instance, I see the JSON structure that might be helpful to reference
```
{
"text": "message 1",
"extra_responses": [
{
"text": "message 2
},
{
"text": "message 3"
}
]
}
```

Docs for multiple responses from a slash command

---

site/content/integrate/slash-commands/_index.md

These params were added per the following PRs:
https://github.com/mattermost/mattermost-server/pull/9878
https://github.com/mattermost/mattermost-server/pull/9836
I noticed that `trigger_id` is missing from the params in the documentation. Is this something that should be documented for custom slash commands?

[MM-9937] [MM-9938] slash command response parameters update

---

site/content/contribute/mobile/developer-setup.md

Document out of memory error in running mobile app.
I've only encountered this on MacOS and I'm not sure how it goes with other OS.

Document out of memory error in running mobile app

---

site/content/contribute/webapp/developer-setup.md

In Developer Setup for Web App, mattermost-webapp is installed in `$(go env GOPATH)/go/src/mattermost/`. I seem it's so strange because of the following reasons:
1. mattermost-server is installed in `$(go env GOPATH)/src/github.com/mattermost/`
1. `$(go env GOPATH)/src/github.com/mattermost` is created at before the command.
1. In Step 5, A symlink is created with `$(go env GOPATH)/src/github.com/mattermost/mattermost-webapp/dist`
`$(go env GOPATH)/go` is probably a typo for `$(go env GOPATH)`.
I've confirmed that modified commands work correctly and all tests are passed.

Fix typos from $(go env GOPATH)/go to $(go env GOPATH)

---

site/content/contribute/webapp/end-to-end-tests.md

This PR adds a troubleshooting guide whenever Cypress failed to start after running `npm run cypress:run`
Screenshot:

Add E2E troubleshooting

---

site/content/extend/plugins/server/hello-world.md
site/content/extend/plugins/webapp/hello-world.md

This PR migrates all plugin manifest related docs to use JSON for the manifest. 
Ref https://github.com/mattermost/mattermost-server/issues/10173

Migrate plugin manifest references from yaml to JSON

---

site/content/contribute/getting-started/core-committers.md

``sousapro`` and ``prixone`` were earlier promoted by Lindy.

Adding list of community maintainers

---

site/content/contribute/server/developer-setup/centos.md
site/content/contribute/server/developer-setup/ubuntu.md

After installing docker, sudo permission was required to run docker and hence the subsequent 'make' command was failing to run the server. By adding the user to the docker group, this can be resolved.

Added command to avoid permission issue while running docker

---

site/content/contribute/server/developer-workflow.md

When I set up the mattermost-server/webapp repos locally, I couldn't figure out who to create a new user to log into mattermost with. Adding two commands to the developer flow on how to create a user on initial setup.

Update developer documentation

---

site/content/contribute/desktop/_index.md
site/content/contribute/getting-started/_index.md
site/content/contribute/mobile/_index.md
site/content/contribute/redux/_index.md
site/content/contribute/webapp/_index.md
site/content/contribute/webapp/end-to-end-tests.md

Update help wanted issue query to a permalink which redirects from https://mattermost.com/pl/help-wanted-mattermost-server to the appropriate query.
The GitHub help wanted issue query changed, breaking all existing links. By using a permalink, we'll only need to update the link once by fixing the redirect from https://mattermost.com/pl/help-wanted-server
This is consistent with redirects we use in the product. Moreover, by specifying the repo makes it clear which repository the link redirects to. The list of pages and their redirects are listed below
1 - https://mattermost.com/pl/help-wanted-mattermost-server
- redirects to https://github.com/mattermost/mattermost-server/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3A%22Help+Wanted%22+label%3A%22Tech%2FGo%22
2 - …

Update help wanted issue queries

---

site/content/internal/sustained-engineering.md

Fix a minor rendering issue:
becomes:

fix bullet formatting on Sustained Engineering Team

---

site/content/extend/plugins/overview/_index.md

Links to the sample and demo plugins are already at the top of the overview section, but community is having trouble seeing/finding them.
Updated overview section to make it easier to see the references for Sample and Demo plugins. Other suggestions welcome

Update overview section for plugins

---

site/content/contribute/getting-started/contribution-checklist.md

The link in this page https://developers.mattermost.com/contribute/getting-started/contribution-checklist/ to the contributions-without-tickets page is broken. It's missing the "getting-started" directory in the path. The link in the sidebar is correct, however.

Bad link to contributions-without-ticket

---

site/content/contribute/getting-started/core-committers.md
site/content/internal/rd-teams.md

Add @ali-farooq0 and @marianunez to the list of core committers, and update to reflect the new toolkit team.

add Ali & Maria

---

site/content/contribute/getting-started/contribution-checklist.md
site/content/extend/plugins/_index.md
site/content/extend/plugins/example-plugins.md
site/content/extend/plugins/migration.md
site/content/extend/plugins/overview/_index.md
site/content/extend/plugins/server/hello-world.md
site/content/extend/plugins/webapp/actions.md
site/content/extend/plugins/webapp/hello-world.md

The `mattermost-plugin-sample` repo is being renamed to `mattermost-plugin-starter-template`. As a result, any references to the original name in documentation needs to be updated, including this repo.
https://mattermost.atlassian.net/browse/MM-14189

Update references to "mattermost-plugin-sample" to be "mattermost-plugin-starter-template"

---

site/config.toml
site/layouts/partials/head.html

Add new homepage link to the admin docs, so developers who have setup their environments can understand how to login to Mattermost, then use it properly as an administrator.
As per JIRA https://mattermost.atlassian.net/browse/MM-16557

MM-16557 Add homepage link to admin docs 

---

site/content/contribute/webapp/end-to-end-tests.md

Update per latest /cypress folder restructure
Reference: https://github.com/mattermost/mattermost-webapp/pull/3044

MM-16704 Update per latest /cypress folder restructure

---

site/config.toml
site/content/internal/onboarding/new-staff-guide.md
site/layouts/partials/head.html

I'm not sure why all three commits of mine are here in this one branch, but I will assume this will all get squashed and merged together. @amyblais - should I be doing something differently?
- Add Marketo Code to header on all pages
- Add `Admin Docs` link to navbar of site
- Remove a useless link from the onboarding page

Remove useless link from developers.mattermost.com

---

site/content/contribute/server/developer-setup/centos.md
site/content/contribute/server/developer-setup/ubuntu.md
site/content/contribute/server/developer-setup/windows-wsl.md

Some developers have got older versions installed already. This step helps to avoid multiple Go installations in the same directory.

Remove /usr/local/go before installing over an existing version

---

site/content/contribute/server/developer-workflow.md

The example go test CLI command in the developer docs points to a test that does not exist in latest master.
The suggestion is to replace:
> For example, if you wanted to run **TestPostUpdate** in **api**/post_test.go, you would run the following:
> 
> go test -v -run='**TestPostUpdate**' **./api**
With
>For example, if you wanted to run **TestUpdatePost** in **app**/post_test.go, you would run the following:
>
>go test -v -run='**TestUpdatePost**' **./app**
The suggestion to use the test `TestUpdatePost` from the ./app folder, instead of the ./api4 folder, is because the ./app folder name has been static, whereas the ./api folder name has changed.

Update example server test name and directory

---

site/content/contribute/getting-started/code-review.md
site/content/contribute/getting-started/labels.md

As discussed in today's Developer Meeting, we're going to block all changes on a `2: QA Review` step, done concurrently with `2: Dev Review`. Not every pull request requires an exhaustive QA review, but it is the PM or QA tester's responsibility to determine this.
(Labels in GitHub to be updated once this PR is approved.)

Require `2: QA Review` before merging

---

site/layouts/partials/head.html

Another marketing request - as per MM-17287 https://mattermost.atlassian.net/browse/MM-17287
This helps our Account based sales system to track people who come to various MM sites.  It shows which companies are interested in our content.
What it does: https://docs.engagio.com/en/articles/202-web-tracking-script
> The Javascript snippet above asynchronously loads the actual Javascript that will run on your site. Our Javascript code captures high-level details about the page such as the URL and title of the web page, then sends it to the Engagio servers as a request for a pixel. It also adds a cookie to determine whether the visitor is visiting for the first time or if we've already seen this anonymous person before.
> 
> Once we get our micro payload with the page view metadata, we do a …

Added engagio tracking scripts

---

site/content/extend/plugins/community_process.md

Included in QA steps as it could be part of testing, but may also fall under PM or Dev ownership
Came up when Chris S tried to test Skype4Business plugin

Add step to have a dedicated instance as part of community plugins

---

site/content/integrate/incoming-webhooks/_index.md

An icon_emoji parameter was added to incoming webhook requests, that overrides the profile icon and the icon_url parameter.
https://mattermost.atlassian.net/browse/MM-16389
Related PRs:
https://github.com/mattermost/mattermost-server/pull/11586
https://github.com/mattermost/mattermost-webapp/pull/3074
https://github.com/mattermost/mattermost-mobile/pull/2961
https://github.com/mattermost/mattermost-redux/pull/876
https://github.com/mattermost/docs/pull/2832

[MM-16389] Reference icon_emoji parameter for webhooks

---

site/content/contribute/server/developer-setup/osx.md

Elasticsearch may need more than the 2GB allocated by default to the Docker Engine

Add note regarding how to solve elasticsearch initialization issues

---

.travis.yml
site/content/contribute/mobile/push-notifications/_index.md
site/content/contribute/mobile/push-notifications/service.md
site/content/internal/mobile-build-process/_index.md
site/layouts/blog/single.html
site/layouts/partials/page-edit.html
site/layouts/partials/sidebar.html
site/layouts/shortcodes/note.html
site/themes/layouts/partials/nav.html

This PR:
- Bumps the Hugo version for the build
- Fixes problems with the `note` shortcode with Hugo >0.54
- Fixes some depreciations and warnings
Please note that the code is still compatible with older Hugo versions.

Bump hugo version

---

site/content/contribute/mobile/developer-setup/_index.md

According to this issue (https://github.com/mattermost/mattermost-mobile/issues/2480), from 1.15 release onwards Android 5/6 Support is dropped, thus it's essential to reflect this information correctly in the doc to smoothen project setup for new contributors like myself, which assumed Android 6 is good to go.

Update the minimum Android build requirements to Android 7 or above

---

site/content/contribute/webapp/end-to-end-tests.md

Add guidelines on folder structure
- naming of subfolder which is based from "Sheet tab" of release testing spreadsheet
- where to put those that requires enterprise license to run the test

Update guidelines on E2E folder structure

---

site/content/extend/plugins/helpers.md

This addition to the plugin documentation explains the purpose of plugin helpers and guides developers on when to extend using same.

document plugin helpers methodology

---

site/content/contribute/server/system_console.md

This adds steps on how to edit the config to the documentation as per request made by Mattermost user `joram`.
Issue #363 
---------------
Please let me know if this is not the best placement for this information.

Add 'How to update the config' to documentation

---

.travis.yml

Bumping the hugo version to keep in in sync with the latest release. There have been problems in the past where we let the version get async to much which caused problems.

Bump hugo version to 0.58.3

---

site/content/contribute/server/developer-setup/arch.md
site/content/contribute/server/developer-setup/centos.md
site/content/contribute/server/developer-setup/osx.md
site/content/contribute/server/developer-setup/ubuntu.md
site/content/contribute/server/developer-setup/windows-wsl.md
site/content/contribute/server/developer-setup/windows.md

Removing GOPATH in the developer guide based on #380. Also, I changed the numeration in some guides.
Fixes #380

Get rid of GOPATH in the developers setup guide

---

site/content/contribute/team_contributions/_index.md

Adding the Team page (migration from here: https://www.mattermost.org/team/)
The idea is to remove that server soon, so migrate pages that are useful for community
adding @lindy65 since her update this page :)

add mattermost team contributors page

---

scripts/plugin-godocs.go
site/layouts/shortcodes/plugingodocs.html

- Modify scripts/plugin-godocs.go to add tags to JSON:
- Each "@tag" found in method comments is added to new "Tags" array attribute for each method
- A global "Tags" attribute is also appended at same level as "Methods"
- Modify HTML layout to handle "Tags" in server API method index
- No impact if no "Tags" attribute is found
https://mattermost.atlassian.net/browse/MM-18676 aka https://github.com/mattermost/mattermost-server/issues/12265
Not so easy to do and test, as it touch several scripts that are not covered by tests. Would be glad to have your feedbacks! If we achieve something on this side, there will be another PR in `mattermost-server` to add correct tags to `api.go` methods. 
I did some choices that are not specified in ticket (or different) : 
* Replaced `@memberOf` by `@tag` …

[MM-18676] Add tags to sort plugin server API methods

---

site/content/contribute/getting-started/_index.md

Creating a placeholder page until Marketing has added the appropriate redirect.
Related docs repo PR here: https://github.com/mattermost/docs/pull/3034

Update help wanted issue link

---

site/content/contribute/server/developer-setup.md
site/content/contribute/server/developer-setup/centos.md
site/content/contribute/server/developer-setup/ubuntu.md
site/content/contribute/server/developer-setup/windows-wsl.md

Hello! :wave: 
This is my first PR, thanks a lot for reviewing it.
As I was going through the steps described in the [server dev setup document](https://developers.mattermost.com/contribute/server/developer-setup/), I noticed this minor mismatch where the `wget` command is downloading the Go source package and not the Linux one which is referenced in the `tar` command from the next line.
I have also added "Fedora 31" to the last tab since I am executing those steps on said distro. :slightly_smiling_face: 
Thanks!

Fix wget command referencing Go src tarball instead of Linux one

---

site/content/contribute/server/developer-setup/arch.md
site/content/contribute/server/developer-setup/centos.md
site/content/contribute/server/developer-setup/osx.md
site/content/contribute/server/developer-setup/ubuntu.md
site/content/contribute/server/developer-setup/windows-wsl.md
site/content/contribute/server/developer-setup/windows.md

The developer docs mention `make stop-server` to stop the running server, but this does not stop the docker containers started by `make run-server`. 
Added a sentence about `make stop-docker` to stop and clean up the running docker containers.

document how to shut down and clean up docker containers

---

site/content/contribute/redux/actions.md

Shouldn't it be "More complicated calls will need to dispatch ~~the~~ different request actions as necessary."? What does `the` refer to?

Remove unneeded "the" in one of the steps of adding an action

---

site/content/contribute/redux/selectors.md

Testing `an Action` should be `a Selector`

Fix typo in the heading for testing a selector

---

site/content/contribute/getting-started/code-review.md

It was agreed during the developers meeting on 20-Nov-19 to give precedence to reaching out to a participating team member in a PR before pinging Jason or Ben.

Update the order of who to reach out to when seeking a review

---

site/content/contribute/getting-started/core-committers.md
site/content/internal/rd-teams.md

I'm not sure who usually reviews, but I see @lieut-data you've made some changes recently so requesting your review. Amy's for editor review.
----
FYI @justinegeffen @adamjclarkson @etoaster 
Adam/Eric: For R&D list, I added you under "Other" while we figure out how the new product and engineer structure work together.

Add Justine Geffen, Eric Sadur and Adam Clarkson to core committers + R&D staff list

---

site/content/contribute/getting-started/core-committers.md

Adding as Build Enginerr
- @elisabeth.kulzer
- @jason.deland
Removing:
- bob not part of the company anymore

Add build engineer and remove non member

---

README.md

I've updated the build status badge in the readme given that automatic builds are now run at CircleCI: https://github.com/mattermost/mattermost-developer-documentation/commit/25f30e65d5087cfd1252bfabdb97fa447c20b2fc
none

update build status badge to point to current one

---

site/content/internal/writing-a-blog-post.md
site/layouts/blog/single.html
site/layouts/partials/blogauthor.html

Blog posts can now be mention more the one author. This is done by setting `author_2`, `github_2` and `community_2` in the front matter. While this approach is a bit hacky, it allows backwards compatibility.
https://mattermost.atlassian.net/browse/MM-21533

Allow two authors in Developers Blog

---

.github/workflows/notify-mm-blog.yml

The GH action that checkout the repo by default (now) just check out the current commit and we need more history to compare what changed.
This Pr fix this issue https://github.com/mattermost/mattermost-developer-documentation/commit/c2f917b9dfbf482ebe3e38811f9c4bfdc7e3acb7/checks?check_suite_id=393748998

when checkout fetch the all history

---

.github/workflows/notify-mm-blog.yml

Make sure to only `grep` metadata from the Front Matter, not the complete blog post. I've triggered the action for the last two posts manually.

Fix gh actions for blog posts

---

.circleci/config.yml

Bumping the hugo version to keep in in sync with the latest release. There have been problems in the past where we let the version get async to much which caused problems.

Bump hugo version to 0.62.2

---

.circleci/config.yml

https://developers.mattermost.com/contribute/server/developer-setup/ was broken with https://github.com/mattermost/mattermost-developer-documentation/pull/494 and the quick fix in https://github.com/mattermost/mattermost-developer-documentation/pull/508 did work on my local instance.
Let's just revert the change and fix all issues _when_ bumping the hugo version in the future.
https://community-release.mattermost.com/core/pl/3izsnipc8inymdar4twpi5wioe

Revert "Bump hugo version to 0.62.2 (#494)"

---

cmd/plugin-godocs/plugin-godocs.go

Keep track of the types seen to avoid listing duplicates. The duplicates are seen as a result of needing to iterate over the test variation of the package to extract examples and such.
Fixes: https://github.com/mattermost/mattermost-developer-documentation/issues/460
Fixes: https://mattermost.atlassian.net/browse/MM-21107

MM-21107: eliminate duplicate API listing

---

site/config.toml
site/content/contribute/server/developer-setup.md

Hugo v0.60.0 switched from Blackfriday to Goldmark.  In this transition, they disabled some html tags in markdown files.  This allows html.
https://gohugo.io/news/0.60.0-relnotes/
Fixes https://github.com/mattermost/mattermost-developer-documentation/issues/506

Allow "unsafe" mode to use html in hugo source

---

site/content/contribute/server/developer-setup/ubuntu.md

This change delimits a link with less-than, greater-than symbols "< >" to avoid surrounding text from being absorbed into it.  In my tests,
```
3. Install Go (modify installation to latest Go version from https://golang.org/dl/):
```
effectively had a link at the end pointing to `https://golang.org/dl/):` instead of the intended `https://golang.org/dl/`. 
None.  Minor fix.

Stopped the `):` from getting absorbed into the link

---

site/content/contribute/mobile/push-notifications/service.md

The Mobile App Push Notification Service page got an update to its Ubuntu based content; It now describes creating a systemd service and explains how to use the logging.
This update has no ticket, but was requested as this guide is referenced in the Mobile Deployment Guide.

Push Notification Service update for Mobile Deployment Guide

---

site/content/contribute/getting-started/_index.md

Fixes https://github.com/mattermost/mattermost-server/issues/13750.
I removed the signup link in case this bug happens again.

Update link in "getting started" page

---

site/layouts/shortcodes/plugingodocs.html

Switch from [godoc.org](godoc.org) to [pkg.go.dev](https://pkg.go.dev), fixing broken links from the generated plugin documentation since the latter site is modules aware.
Fixes: https://mattermost.atlassian.net/browse/MM-22187

MM-22187: switch to pkg.go.dev

---

Makefile
legacy.mk

- Place `.PHONY` in front of each target to ensure it doesn't get forgotten
- Make use of `hugo -s` to set the source
- Add `make run` as an alias of `make dev`, as `make run` is the more common term

Add make run

---

site/content/contribute/webapp/developer-setup.md

While running through installation it took a moment to understand that "Install dependencies" wasn't a separate instruction from the bullet points below it. Adding an indentation to the bullet points and a colon after "Install dependencies" makes this more clear imo.

Adjust formatting for "Install dependencies"

---

.github/workflows/notify-mm-blog.yml

generate empty mattermost.json when there is no changes
merge this after https://github.com/mattermost/action-mattermost-notify/pull/4 get merged
fixes: https://github.com/mattermost/mattermost-developer-documentation/pull/496#issuecomment-574144400
Fixes https://github.com/mattermost/mattermost-developer-documentation/issues/497

generate empty mattermost.json if there is no changes

---

site/content/contribute/server/developer-workflow.md

…
I was [chatting with Jesse Hallam](https://community.mattermost.com/core/pl/q5om5tphxbgj3gmfa9368zqjyh) who recommended this command.  When I went to go read documentation on it, I [couldn't find it anywhere](https://www.google.com/search?q=site:developers.mattermost.com+%22make+config-reset%22).  This seemed like a good place for it so others know about it!
This is a one line fix, so there's no ticket.  I believe this is OK [per the guidelines](https://developers.mattermost.com/contribute/getting-started/contributions-without-ticket/), but lemme know if not!

Add missing `make config-reset` to "useful make commands" in developer-workflow

---

.github/workflows/notify-mm-blog.yml

Adding double quotes to the blog title is causing issues with deployment. 
Added trimming of additional quotes for the blog title in the pipeline.

Fix quoting issue.

---

.circleci/config.yml

As reported by @cpoile https://developers.mattermost.com/integrate/incoming-webhooks/ doesn't render the http code sample correctly. This was broken in Hugo `v0.59.0` and was fixed in Hugo `v0.65.0`. The bug report is https://github.com/gohugoio/hugo/issues/6877.
I opted to upgrade to `0.67.1`, because I would like to stay up to date with the version devs use. 1/5
https://community.mattermost.com/core/pl/oadox9mwj788jq1bch1hyou5za

Bump hugo version to 0.67.1

---

site/layouts/blog/list.html
site/static/css/styles.css

Add pagination for blog page.
Sample page: https://kaakaa.github.io/mattermost-developer-documentation/blog/
Fixes #510 
Pagination with this PR looks good to me, but code looks weired due to the order of entries. For example, `.Paginator.Next.URL` has the link to previous posts and vice versa.
https://github.com/mattermost/mattermost-developer-documentation/compare/master...kaakaa:blog-pagination?expand=1#diff-eaf3f98942f1231e6bf736e8a26e02ddR22
What do you think about this?
If you don't like this, we might use [Hugo's default pagination template](https://gohugo.io/templates/pagination/).  The template makes code simple, but it looks a little messy.

Add pagination for blog page

---

site/content/extend/plugins/webapp/reference.md

Fixing import paths in plugin webapp documentation.
Fixes https://github.com/mattermost/mattermost-developer-documentation/issues/489

Addresses Request for Documentation: Typo in plugin webapp developer documentation #489

---

site/content/contribute/getting-started/core-committers.md
site/content/internal/rd-teams.md

Add @agarciamontoro, @larkox and @angeloskyratzakos to the list of core committers. Update the R&D teams to reflect the recent team changes.

update core committers, r&d teams

---

site/content/internal/plugin-release-process.md

`/mb cutplugin` requires a `--repo` parameter without the leading `mattermost` organization.
@crspeller, you were asking today for context into the `cutplugin` command. While you can still tag a release manually and get unsigned artifacts, @DSchalla specifically asked for a workflow that would ultimately enable explicit building+signing, to be eventually gated by the security team. Open to process improvements here!

fix plugin release example

---

site/content/contribute/server/developer-workflow.md

The web app workflow document already has a step for running `make i18n-extract` when adding/modifying the localization strings. This PR adds the same step to the server workflow, as it is also needed.
https://mattermost.atlassian.net/browse/MM-23588

MM-23588: Document i18n-extract in Server workflow

---

site/content/internal/plugin-release-process.md

As part of https://github.com/mattermost/matterbuild/pull/28, we can now cut releases using arbitrary commits. Including `--force` and `--commitSHA` matterbuild examples.

Include --force and --commitSHA examples

---

site/content/integrate/incoming-webhooks/_index.md

That's it.. just a missing comma and a few extra quotes.

Webhooks example, fix invalid json

---

site/content/contribute/getting-started/contribution-checklist.md

This style guide page was deleted as the page was outdated. I have also submitted a pull request to update the link in another page this guide was referenced in: https://github.com/avasconcelos114/mattermost-themes/pull/46
I didn't see other references to this page based on Google Analytics.

Remove a step to follow style guide from contribution checklist

---

site/content/extend/plugins/webapp/reference.md

Both the inline code `registerPlugin` and the code block below need a blank line before to render properly.
Before:
After:
--

Fix code rendering in plugin docs

---

scripts/package-lock.json
scripts/package.json
scripts/plugin-jsdocs.js
site/layouts/shortcodes/pluginjsdocs.html

@metanerd investigated the latest failed build in master and narrowed it down to this change: https://github.com/mattermost/mattermost-webapp/commit/397e4b65a610cfc81ab8076dbf9348c71d4d4872#diff-99e11b3b61425aff9ef2e561dd706b2cR600
After some more investigation, it looks like [esprima](https://github.com/jquery/esprima) does not recognize the [spread syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax) in its latest release, even if they have it on master: https://github.com/jquery/esprima/issues/1927
This PR replaces esprima with [espree](https://github.com/eslint/espree), a more up-to-date fork.
See a bit more of context in this thread in Mattermost: https://community-daily.mattermost.com/core/pl/4tewph9mjpyfxywr9ygyg8syec
--

Replace esprima with espree

---

site/content/contribute/server/system_console.md

This adds the `mattermost-webapp`  directory prefix to the documented line. A new person might look in the `mattermost-server` directory for the path and will lose time looking for it.

Accurate path for exposing System Console settings

---

site/content/contribute/webapp/developer-setup.md

The `mattermost-webapp/dist` directory doesn't exist in our clone. We should create it first, then link to it in order to avoid confusion.
(None)

Make the `dist` directory first

---

site/content/contribute/getting-started/core-committers.md

Adding @avasconcelos114 as core committer for webapp and mobile repos 🎉  🙌  💯 
More to come once this PR is merged and is official.. :)

Adding @avasconcelos114 as core committer for webapp and mobile repos

---

site/layouts/partials/notification.html
site/static/css/bar.css

With this PR, clicking the banner's X no longer scrolls to the top of the page
Fixes https://github.com/mattermost/mattermost-developer-documentation/issues/679

Fix "We're hiring" banner's close button

---

site/content/contribute/webapp/end-to-end-tests.md

Add missing step from cypress guide about running the storybook.

Add a point about running storybook for e2e tests.

---

site/content/extend/plugins/community-plugin-marketplace.md

As discussed on Community there is no need to prohibit copy left plugins in the Marketplace.
https://community.mattermost.com/private-core/pl/mk66rxs8etbffd8gc9bg9mfone

Allow copy left plugins in the Marketplace

---

site/layouts/blog/list.html
site/layouts/blog/single.html

The pull-request adds the footer used on multiple pages across the site to the blog section of the website
It also resolves issue #685

Add website footer to blog section

---

site/layouts/blog/list.html

Blog posts are not showing in order as mentioned in #686
To fix this, we need to make a small change in `site/layouts/blog/list.html` to add sorting.
Fixes https://github.com/mattermost/mattermost-developer-documentation/issues/686
Hope this helps and stay safe!
Happy Hactoberfest2020 :fireworks: 
Hiren

[GH-686] sorting blog posts by date

---

site/content/contribute/mobile/unsigned/android.md
site/content/contribute/mobile/unsigned/ios.md

The links to scripts that are needed in these docs were not working correctly.  There was an extra `/` appended in the url. Updating this

Fixing links to download app signing scripts

---

site/static/scripts/sign-android

apktool seems to unpack the apk files to different paths.  Admittedly I don't understand the inner workings of whats happening, but I noticed the unpacked apk had smali files at a different path than what was expected by the `sign-android` script.
My `apktool` version (in case its relevant):
```
Apktool v2.5.0 - a tool for reengineering Android apk files
with smali v2.4.0 and baksmali v2.4.0
```
I also shifted `mv $SRC $DEST` down a few lines as this seemed to be done too early for the `sed` modifications to apply.

Modified `smali` related paths based apktool change

---

site/static/css/styles.css

- prevented content from overflowing the screen on small-sized mobile phone devices, such as iPhone 5/SE
- deleted unused code block with css class `.table-striped` and no specified styles
**Note:** I have moved all the css media queries to the end of the file to prevent styles overwrite which is why there seem to be so many changes in the diff.
Fixes https://github.com/mattermost/mattermost-developer-documentation/issues/722
Here is an example of the proposed changes, shown on iPhone 5:
**Proposed fix** (left) vs. **Current state** (right)

[GH-722] - Fix content wider than screen on mobile

---

site/content/contribute/server/rest-api.md

Hey, first time committer here (starting my new job at MatterMost from March, but already warming up).
I noticed a syntactical error in the Go example on adding API endpoints, this fixes it. Bonus: it indents the comments.
No ticket, didn't seem worth it since it's a trivial fix.

REST API Docs: Fix syntax error in Go code sample and indent

---

site/layouts/_default/list.html
site/layouts/_default/single.html
site/layouts/_default/taxonomy.html
site/layouts/blog/list.html
site/layouts/blog/single.html
site/layouts/index.html
site/layouts/indexes/tag.html
site/layouts/partials/gtm-body-noscript.html
site/layouts/partials/head.html

The snippets that were baked into the `head.html` partial have been moved to a GTM container for developers.mattermost.com. That GTM container snippet has been added to the `head.html` and the `<noscript>` fallback has been added to all html layouts.
https://mattermost.atlassian.net/browse/MAR-225

Replaced inline 3rd-party snippets with GTM container

---

site/content/internal/gitlab-omnibus.md

It turns out they were in the process of changing this when I wrote the documentation, so we only need to do changelog entries using the new approach instead of the old one.

Update steps for updating GitLab Omnibus's changelog

---

site/content/contribute/desktop/code-signing.md

I've been trying to use `osslsigncode` and used your instructions. I found a few typos which are fixed here.

typo for osslsigncode

---

site/content/integrate/apps/using-third-party-api/_index.md

Changed terminology from Desktop App to Desktop client for clarity. Adjusted some formatting for calls/commands.

Changes to terminology and formatting  - third-party API doc

---

site/content/integrate/getting-started/how-should-i-integrate.md

The Apps introduction page is a better landing experience for people who are first learning about the Apps framework. This PR changes the link to https://developers.mattermost.com/integrate/apps/
N/a

Change Quickstart link for App integration

---

site/content/integrate/apps/deployment/_index.md
site/content/integrate/apps/quick-start-go/_index.md
site/content/integrate/apps/quick-start-js/_index.md

This PR removes the deployment sidebar link and adds the developer mode setting requiremenet.
https://mattermost.atlassian.net/browse/MM-35761

[MM-35761] Remove references to AWS provisioning and setting AWS server variables

---

site/content/contribute/mobile/build-your-own/ios.md

Remove weird an unnecessary `\` on the environment variable names

Update iOS env vars

---

site/content/integrate/apps/bindings/_index.md
site/content/integrate/apps/interactivity/_index.md
site/content/integrate/apps/quick-start-go/_index.md
site/content/integrate/apps/quick-start-js/_index.md

The icon link in https://developers.mattermost.com/integrate/apps/quick-start-js is not working because it's pointing to https://github.com/mattermost/mattermost-plugin-apps/raw/master/examples/go/helloworld/icon.png instead of https://github.com/mattermost/mattermost-plugin-apps/raw/master/examples/go/hello-world/icon.png.

Fix App quick start links to point to examples/go/hello-world instead of helloworld

---

site/content/contribute/getting-started/branching.md

Clarify that for approved cherry-picks with no further changes from the original PR, we can merge without further review.
None

clarify cherry-pick happy path

---

site/content/integrate/apps/bindings/_index.md

Be a bit more explicit on when the bindings will be fetched.
The reasoning behind this change is to make clear that threads and posts will always have the bindings according to their context. 
https://github.com/mattermost/mattermost-mobile/pull/5563
https://github.com/mattermost/mattermost-webapp/pull/8439

Be more explicit about bindings fetching

---

site/content/integrate/apps/interactivity/_index.md

As in https://github.com/mattermost/mattermost-developer-documentation/pull/932, I piggybacked two different changes on this PR:
- Open forms from any location. Now, if a binding for embedded bindings has a form, it will open directly a modal form.
- Binding filtering. We added several filters to forms and bindings, to make sure they are well formed. Updated the documentation to take those in consideration.
Open form in any location
https://github.com/mattermost/mattermost-mobile/pull/5665
https://github.com/mattermost/mattermost-webapp/pull/8784
Filtering:
https://github.com/mattermost/mattermost-webapp/pull/8782
https://github.com/mattermost/mattermost-mobile/pull/5655

Added info about Open forms from other bindings, and updated bindings requirements. (Part 2)

---

site/content/integrate/apps/bindings/_index.md

I piggybacked two different changes on this PR:
- Open forms from any location. Now, if a binding for post_menu or channel_header has a form, it will open directly a modal form.
- Binding filtering. We added several filters to bindings, to make sure they are well formed. Updated the documentation to take those in consideration.
Open form in any location
https://github.com/mattermost/mattermost-mobile/pull/5665
https://github.com/mattermost/mattermost-webapp/pull/8784
Filtering:
https://github.com/mattermost/mattermost-webapp/pull/8782
https://github.com/mattermost/mattermost-mobile/pull/5655

Added info about Open forms from other bindings, and updated bindings requirements.

---

site/content/integrate/admin-guide/admin-bot-accounts/_index.md

Fixed the API link we use, and added some additional bullets on how the flow for refreshing a bot token would work.

Fix bot token expiry docs links

---

site/content/contribute/server/style-guide.md

- Added a section on how to use generics.
- While here, we also remove the comment on the model package
since 6.0 is already released and changes have been made to make
everything consistent.

Comment on generics

---

site/content/contribute/mobile/build-your-own/android.md

Updated the documentation for building own Android app by adding a new env var: ANDROID_BUILD_TASK
https://github.com/mattermost/mattermost-mobile/pull/5884

Added info about ANDROID_BUILD_TASK env var in building Android app docs

---

site/layouts/partials/nav.html
site/static/css/styles.css

This PR fixes the menu styling at smaller breakpoints. Specifically, the top-level nav items wrap to two lines before we get to the mobile menu. I've made a couple reductions in font size and padding to remediate the issue.
cc: @cwarnermm – Not sure who else to tag as a reviewer on this. I've temp tagged Ben, but feel free to change if you have other ideas.
I'm just gonna view the preview site, and then remove the WIP tag.
Thanks!

Fix menu styles for smaller breakpoints

---

site/static/css/bar.css

Similar to https://github.com/mattermost/mattermost-developer-documentation/pull/857, this PR fixes the issue where the the navbar covers the header of a permalink.
When the "Workflow" header link is clicked:
Before
After

Fix header permalinks

---

site/content/contribute/server/developer-setup.md
site/content/contribute/server/developer-workflow.md

This PR adds some information about how to customize some variables from the Makefile and provides documentation on using a custom `docker-compose.override.yaml` file.
N/A

Add info to customize Makefile and docker-compose

---

site/config.toml

Changing the notification on developers.mattermost.com back to the "We're hiring!" with a link to mattermost.com/careers.
No Jira link

Remove research request, change it back to hiring

---

site/content/contribute/getting-started/code-review.md

This includes mostly minor tweaks, but also stops linking out to https://handbook.mattermost.com/contributors/contributors/core-committers given [the plan](https://github.com/mattermost/mattermost-handbook/pull/993) to deprecate that document.
N/A

Refresh code review guidelines

---

site/content/contribute/focalboard/_index.md
site/content/contribute/focalboard/mattermost-boards-setup-guide.md
site/content/contribute/focalboard/personal-server-setup-guide.md
site/content/contribute/getting-started/_index.md
site/content/integrate/plugins/community_process.md

This PR migrates the [Focalboard developer documentation](https://mattermost.github.io/focalboard/) into the Mattermost developer documentation. The Focalboard website undergo a redesign soon, and as a result we will be losing the "Contribute" link in the header. All of those pages will need a new home. Several of those pages are duplicative of things already in the Mattermost developer documentation, so they were removed and relevant links were provided instead. Wherever unique information was mentioned on those pages about the Focalboard contribution process, those callouts have now been moved to the initial Focalboard page in the developer documentation so they stand out more clearly.
Because this PR will change where developer resources will live, I will also submit a separate PR to …

Migrate in Focalboard developer documentation

---

site/content/contribute/webapp/e2e/running-e2e.md

After the restruction of the e2e folder, the user needs to run the npm commands from `e2e/cypress` not `e2e/`
https://mattermost.atlassian.net/browse/MM-43112

[MM-34112] specify the user to run in the e2e/cypress directory

---

.config/notice-file/Readme.md
.config/notice-file/config.yaml
LICENSE.txt
NOTICE.txt

PR contains changes to have Notice.txt file in the repository. We added Python support to our notice-file-generator tool and configure this repository with that pipeline.
Required configuration about notice file generation is stored at `.config/notice-file` folder.
https://mattermost.atlassian.net/browse/DOPS-1074

Enable Notice.txt generation

---

site/content/contribute/server/developer-setup.md

The change from `interface{}` to `any` requires developers to use Go 1.18 or higher

We are using any instead of interface{} now, min Go version is 1.18

---

site/content/contribute/focalboard/personal-server-setup-guide.md

Updated the [focalboard documentation](https://developers.mattermost.com/contribute/focalboard/personal-server-setup-guide/#building-and-running-standalone-desktop-apps) to inform the developer to run the `make prebuild` step before the `make linux-app` or `make win-wpf-app` or `make mac-app` step.
Related issue #1079
Signed-off by: imasdekar <imasdekar@disroot.org>

update: focalboard instructions for prebuild for standalone desktop app dev setup

---

.github/workflows/preview-env-fork.yml

BaseURL is incorrect for forked PRs that causes preview environment has incorrect base url and that will broke static asset links.

Fix preview environment for forked PRs

---

Makefile
scripts/package-lock.json
scripts/package.json
scripts/plugin-jsdocs.js

This change allows the docs build process to complete in a shorter time by not re-cloning the [mattermost-webapp](https://github.com/mattermost/mattermost-webapp) repo with each execution. The webapp plugin registry (`mattermost-webapp/plugins/registry.js`) is fetched directly from GitHub by the `plugin-jsdocs.js` script instead.

Improve docs build time

---

site/content/contribute/more-info/webapp/e2e/running-e2e.md

We have removed the storybook from the mattermost-webapp, so this step isn't required anymore.
Confusing for new contributors.
https://community.mattermost.com/core/pl/j6jx6c9oapggdezs31dukkmfry
NA

Remove storybook step from local e2e setup

---

site/content/contribute/more-info/webapp/e2e/running-e2e.md

Change Url pointing to cypress.json to point cypress.config.ts
cypress.json doesn’t exist. The codes from that has been migrated to cypress.config.ts and remove the storybook reference

Change Url pointing to cypress.json to point cypress.config.ts

---

site/layouts/partials/sidebar.html

This PR will auto-expand subtopics in the sidebar for pages in the Contribute section only. The Integrate section is not affected.

Auto-expand subtopics in sidebar for the Contribute section

---

site/content/contribute/more-info/webapp/developer-setup.md

Added a note regarding Apple Silicon Macs requiring Rosetta to be installed for al package.json dependencies and libraries to work ok.
I didn't find any Apple oficial documentation regarding the `softwareupdate` command, that's why I just put it in there.

chore(webapp): added note for apple silicon macs

---

site/content/contribute/more-info/server/developer-setup/windows-wsl.md

In the [Setting Up Your Development Environment](https://developers.mattermost.com/contribute/more-info/server/developer-setup/) page, under the Windows WSL section, when you get to step 4, it states:
> Install Go using bash (modify installation to latest Go version from https://golang.org/dl/):
This link does not work anymore and I changed it to https://go.dev/dl/.
Fixes #1158

Wrong Golang Link In WSL Setup

---

site/content/contribute/more-info/mobile/developer-setup/_index.md

Right now the `$` sign was copied from the highlighted command in the UI, so when you want to execute it won't work right away.

Removed $ signs so the commands can be copied with the UI copy button

---

scripts/package-lock.json
scripts/package.json
scripts/plugin-jsdocs.js

The `mattermost-webapp/master/plugins/registry.js` file was converted to TypeScript and renamed to `registry.ts`. This breaks the dev docs build since it's expecting the previous filename and that it contains ECMAScript.
The ECMAScript parsing was replaced by TypeScript parsing by way of `@typescript-eslint/typescript-estree`, which is a mostly drop-in replacement for `espree`. The logic in `plugin-jsdocs.js` was updated to extract function arguments from new locations in the abstract source tree (AST).

Fix broken builds; webapp registry.js migrated to TypeScript

---

site/layouts/_default/single.html

The feedback widget is missing from several docs pages. This PR resolves the issue by adding the feedback widget code to the docs template that was not modified during the original implementation.

Add missing feedback widget to the rest of the docs pages

---

site/content/integrate/apps/authentication/app-to-third-party/_index.md

The hello-oauth example is no longer in the specified URL in the documentation, replaced for the right one.

App oauth2 example fix url

---

.gitlab-ci.yml

The version of Hugo used to build the docs in production is still using v0.92.1 and may be the cause of some rendering errors. This PR updates the version of Hugo to v0.101.0, so it matches the version used in GitHub actions.

Update Hugo version to 0.101.0 for production builds

---

site/content/integrate/slash-commands/_index.md
site/content/integrate/slash-commands/built-in/_index.md

As part of the v7.8 release, moving built-in slash command documentation from the developer documentation to the product documentation site.

Moved built-in slash commands content to prod docs

---

site/content/contribute/more-info/desktop/debugging.md

We added a menu item called 'Show Logs' that points out where the log file is location for ease of use.

Add documentation around the Show Logs function

---

site/config.toml
site/layouts/partials/notification.html

This PR removes the notification banner since the GitLab webinar has passed. A discussion re: a general fallback is being had.
Thanks!

Remove notification bar

---

site/content/integrate/apps/structure/forms/_index.md

Some of the commas provided in the sample JSON objects broke the json syntax. The commas have been removed.

Removed unnecessary commas in JSON examples

---

site/content/contribute/monorepo-migration-notes.md
site/content/contribute/more-info/server/developer-workflow.md

It turns out that some errors people had after doing the monorepo upgrade were because Docker doesn't automatically update some configuration settings used by Docker
https://github.com/mattermost/mattermost-server/pull/22813

Add Makefile target to update development Docker container configuration

---

site/content/contribute/more-info/focalboard/mattermost-boards-setup-guide.md

Added a note to the top of the page alerting users on Mattermost v7.11 and later to reference different setup pages. In the future, when the majority of customers are beyond v7.10, we'll formally retire this page.

Redirect readers to updated dev guide

---

site/content/integrate/apps/_index.md

The developer documentation was missing details on the minimum Mattermost Server version needed to build apps using the apps framework.

Added min server requirements for app framework

---

site/content/contribute/more-info/getting-started/branching.md

Small change to suggest using the same branch name when pushing the new branch. I didn't do that today and ended up somehow pushing my local branch directly to cloud 🤦🏻 
N/A

manual cherry pick doc: suggest a remote branch name for the push

---

site/content/contribute/more-info/server/rest-api.md

Clarify that updating the API no longer requires committing a separate PR to the mattermost-api-reference repository.
None.

Update API documentation steps

---

site/content/contribute/more-info/server/style-guide.md

We have been using generics in some other codebases as well. And it's been a while since it's out. No reason to keep it blocked in the main codebase.

Open generics to be used freely

---

site/content/integrate/apps/deploy/deploy-aws/_index.md

HTTP apps can be used on Cloud. We should make this clear.
https://mattermost.zendesk.com/agent/tickets/41473

Clarify which Apps can be deployed on MM Cloud

---

site/content/integrate/slash-commands/_index.md

Correct the maximum post size documented on the slash commands page. The v5.0 release notes say it is 16383 characters.

Correct max post size on slash command page

---

site/config.toml
site/layouts/partials/nav.html
site/layouts/partials/nav2.html
site/static/js/main.js

This PR adds the 9.0 announce blog to the notification banner, and updates the global nav to align with mm.com.
@cwarnermm – Feel free to adjust the footer links and I'll mirror the changes on mm.com. Will add more reviewers once we're zipped up.
Thank you!

Update notification banner and global nav

---

site/content/integrate/plugins/_index.md

The plugin dev docs currently point to server and webapp quickstart guides, which are pretty outdated and lead new plugin developers down an unproductive path. Maybe we should still link to them for reference, but we generally shouldn't encourage "using" them for a project.

Update plugins development to include dev setup links

---

site/content/contribute/why-contribute/_index.md

The tip component in https://developers.mattermost.com/contribute/why-contribute/#you-want-to-help-with-content
was not rendering the hyperlink properly. After going through the .md file, it has incorrect indentation, so it was unable to build properly. Fixed the indentation and tested locally.
Current view
Corrected view

Fix indentation for correct building of tips section

---

site/content/contribute/developer-setup.md

Since they're the first thing you see in the developer setup guide, I noticed that it's not very clear that the extra steps are for Windows only, so I added a short note to clarify that and remind people that they need to use the WSL versions of things they might already have installed.

Add note developer setup for Windows

---

site/content/integrate/apps/structure/bindings/_index.md

Added correction in the bindings docs to solve the call function issue.
Addresses: https://github.com/mattermost/docs/issues/6821

Incorrect examples in bindings docs page

---

site/content/integrate/plugins/developer-setup.md

This PR adds a basic Tip at the end of the Plugins Overview page that guides the user on how to use .nvmrc in plugin projects.
Fixes #1222

Added Note on usage of .nvmrc in plugin projects

---

site/content/integrate/reference/server/server-reference.md
site/content/integrate/reference/webapp/webapp-reference.md

When this PR is merged, the following redirects will work as expected:
- https://developers.mattermost.com/integrate/plugins/components/server/reference
- https://developers.mattermost.com/integrate/plugins/components/webapp/reference
Both the server and webapp SDK page titles have been updated to include the term "plugin", and now include links back to the Plugin section, developer setup, and developer workflow.

Added missing redirects & links to relevant content

---

site/content/contribute/more-info/server/style-guide.md

Link to https://go.dev/doc/modules/layout instead of providing our own style guide.
https://community.mattermost.com/core/pl/fe9oh9srxiyafjm64p8km1nh3a

Update style guide to reflect standard Go module layout

---

site/content/contribute/more-info/mobile/push-notifications/service.md

This pull request fixes a OpenSSL command in the [Install the Mattermost push notification service documentation](https://developers.mattermost.com/contribute/more-info/mobile/push-notifications/service/), which extracts the private key from a certificate, by adding the `-legacy` option, this is due to since OpenSSL 3.0, the RC2 algorithm has been moved to the `legacy` provider, which is not loaded by default.
Fixes https://github.com/mattermost/mattermost-developer-documentation/issues/1281

[GH-1281] OpenSSL Compatibility: Add -legacy option

---

site/content/integrate/slash-commands/outgoing-oauth-connections/_index.md
site/content/integrate/slash-commands/slack/_index.md

Adjusting page weights for 2 child pages to surface a new Ongoing OAuth connections page in the navigation pane. (Page weights determine page order in the nav and can't be the same across pages).
The generated preview shows the page as expected. Let's merge the PR to see if prod also shows the page.

Updated page weight

---

site/content/integrate/plugins/interactive-dialogs/_index.md

Fix error in the [documentation](https://developers.mattermost.com/integrate/plugins/interactive-dialogs/) to interactive dialogs. In the table in the 'Select elements' section, the rows 'options' and 'help_text' are displaced.
Fixes https://github.com/mattermost/mattermost/issues/16199
Jira https://mattermost.atlassian.net/browse/MM-30075

Update _index.md fix list of fields of select element

---

site/content/contribute/more-info/mobile/build-your-own/android.md

We add documentation on how to update the lock files.
This is dependent on https://github.com/mattermost/mattermost-mobile/pull/7875
NONE

Add graddle lockfile update to the documentation

---

site/content/contribute/developer-setup.md

Update developer-setup.md to provide no-docker setup information

Update developer-setup.md to provide no-docker setup

---

site/content/contribute/developer-setup.md
site/content/contribute/more-info/mobile/developer-setup/_index.md

After creating the issue #1353 (to which I was assigned) I went ahead and made some minor changes to the developer's setup guide. I did leave out the docker permission issue as I believe the error message may be clear enough to lead someone to resolving it relatively quickly.
I also noticed the ruby version in the mobile documentation was not inline with the requirement in the mobile repo so I updated that as well.
#1353

Some tweaks to the developer setup guide

---

site/content/contribute/more-info/mobile/developer-setup/_index.md

After the dependencies bump, we now require Java 17 instead of 11.

Update Java version required

---

site/content/integrate/reference/webapp/webapp-reference.md

When replacing ~channel mention with a link by `PostUtils.formatText`, just specifying `channelNamesMap` as args didn't get a correct result, and it was required to specify `team` arg at the same time. The document doesn't mention this, so it should be added.
N/A
```js
...
// msg1: no options
const msg1 = messageHtmlToComponent(
formatText(`link: ~off-topic`, {}
), true, {});
// msg2: just `channelNamesMap`
const msg2 = messageHtmlToComponent(
formatText(`link: ~off-topic`, {channelNamesMap}
), true, {});
// msg3: `channelNamesMap` and `team`
const msg3 = messageHtmlToComponent(
formatText(`link: ~off-topic`, {channelNamesMap, team}
), true, {});
...
```
<details><summary>Entire code</summary><div>
```js
import React from 'react';
import {getChannelsNameMapInCurrentTeam} from …
```

Add a missing note about plugin webapp utility function (PostUtils.formatText)

---

site/content/contribute/more-info/desktop/build-commands.md
site/content/contribute/more-info/desktop/debugging.md
site/content/contribute/more-info/desktop/packaging-and-releasing.md

A few updates to the Developer docs for Desktop App:
- Updated the command list
- Removed reference to the MSI builder
- Added Dev tools for Calls widget
- Refined the packaging docs
https://mattermost.atlassian.net/browse/MM-58223

Updates to Desktop App developer docs

---

.github/workflows/preview-env-fork.yml
.github/workflows/preview-env.yml

This fixes an issue with the preview environments, which were missing the `site/data/PluginJSDocs.json` file before being pushed to S3, resulting in the `/integrate/reference/webapp/webapp-reference/#registry` paragraph missing the Plugins API reference (see [here](https://developers.mattermost.com/integrate/reference/webapp/webapp-reference/#registry) for how it looks in prod).
https://mattermost.atlassian.net/browse/CLD-6764

Build plugin-data before publishing preview env

---

site/content/contribute/more-info/desktop/developer-setup/macos.md
site/content/contribute/more-info/desktop/developer-setup/windows.md

Updated the Desktop App docs to use `nvm` for macOS and Windows as well as per request: https://hub.mattermost.com/private-core/pl/mojqwu9mmjfczyjk99qaffappo

Update Desktop App docs to use `nvm` on macOS and Windows

---

site/content/contribute/more-info/mobile/build-your-own/_index.md

Looking at the documentation to build the mattermost react native app, and clicking the link to access the CI conf, returned me a 404. So I fixed by providing the new link (previously circleci now github action).

Update documentation link for mobile app builds CI

---

site/content/contribute/developer-setup/_index.md

- Fixes up #1311 and #1351
Fixes broken indents in [Set up your development environment](https://developers.mattermost.com/contribute/developer-setup/).
| before | after |
|-|-|
| ![Developer_setup](https://github.com/mattermost/mattermost-developer-documentation/assets/10229505/1c69039f-e7c3-49aa-8262-15e757a710fb) | TBA |
n/a

Fix indents in "Set up your development environment"

---

scripts/package-lock.json
scripts/package.json
scripts/plugin-jsdocs.js

- Follows up #1098
This change replaces `sync-fetch` with `await` and `node-fetch@3.3.2` as `sync-fetch` does not support `node-fetch` v3 and allow us to avoid `whatwg-url@5.0.0`. `node-fetch@3.3.2` does NOT depend on any version of `whatwg-url`.
n/a
node-fetch 2.x, followed by sync-fetch, does not support Node.js 21 and higher fully as it relies on punycode depending from whatwg-url 5.0.0.
- cf. https://github.com/mattermost/mattermost/pull/27463 (fixing the same problem in the main repo)
- See also https://github.com/larsgw/sync-fetch/issues/29
As is, with Node.js 21+, we can see warning as follows due to dependency to `whatwg-url@5.0.0`:
```
$ make plugin-data                
mkdir -p site/data
go run ./cmd/plugin-godocs > site/data/PluginGoDocs.json
go run ./cmd/plugin-manifest-docs > …
```

Replaces node-fetch v2 (sync-fetch) with node-fetch v3

---

site/content/contribute/more-info/server/style-guide.md

This article was moved out of the language's repo's wiki into a hosted wiki article. Updating the links.
Previous location: <https://github.com/golang/go/wiki/CodeReviewComments>  
New location: <https://go.dev/wiki/CodeReviewComments>
CLA signed.

Update links to Go's 'Code Review Comments'

---

site/content/contribute/good-decisions/fixing-pr-mistakes.md
site/content/contribute/more-info/webapp/e2e-cheatsheets.md
site/content/contribute/why-contribute/_index.md

Removed a duplicate bullet point on the "[Why and how to contribute](https://developers.mattermost.com/contribute/why-contribute/#:~:text=If%20you%E2%80%99d%20like%20to%20contribute%20to%20our%20blog%2C%20website%2C%20or%20social%20media%20content%2C%20you%20also%20have%20a%20few%20options%3A)" page.
~I kept the second bullet point because it's the most recent one added in this [commit](https://github.com/mattermost/mattermost-developer-documentation/commit/b6710ef7#diff-c698222c163287fd3ea03f272506a819a46e32e920f76b65e9367861817e5d6f).~
I kept the first bullet point because the docs recommend, as a [best practice](https://github.com/mattermost/mattermost-developer-documentation/tree/master#:~:text=Links%20that%20navigate%20away%20from%20developers.mattermost.com%20should%20use%20the%20new …

Remove duplicate point and fix date format

---

site/content/contribute/more-info/desktop/developer-setup/redhat.md

Incorrect package manager was referenced as apt in the RHEL developer documentation. Simple change of apt to yum. Utilized yum instead of dnf as most distributions support either or but not all RHEL variants support dnf if someone was to utilize a EL7 variant.

Update package manager name for RHEL developer-setup

---

site/content/contribute/more-info/mobile/developer-setup/_index.md

Complement https://github.com/mattermost/mattermost-mobile/pull/8315 to upgrade to Ruby v3.2.0 for mobile development.
None.

feat: Update Ruby version requirement to 3.2.0

---

site/content/integrate/reference/message-attachments/_index.md

Documentation for: https://github.com/mattermost/mattermost/pull/28018

Doc'd @mention support for pretext, text, & fields[X].value

---

site/content/contribute/more-info/getting-started/contribution-checklist.md

Replaces a link to https://github.com/mattermost/mattermost-api-reference, which is obsolete, to the part of the monorepo that replaces it: https://github.com/mattermost/mattermost/tree/master/api
None.

Replace deprecated API docs repository by up to date link

---

site/static/css/elements-custom.css

Punctuation (brackets, commas) in response samples in API documentation was not showing well due to lack to color contrast with the background
Before - commas and brackets not easily visible:
With PR changes:
N/A

Make API documentation punctuation more visible

---

site/layouts/partials/page-edit.html

Used Claude to update the ``page-edit.html`` partial to use the new URL (https://github.com/mattermost/mattermost/tree/master/api/v4/source) specifically for API documentation pages, while keeping the original URL for all other pages.

Edit on GitHub: Take API docs visitors directly to API YAML source

---

site/content/contribute/more-info/desktop/developer-setup/windows.md

Lately Windows 11 has stopped auto-installing the `wmic` utility, which is needed for some of our scripts to run. This PR adds this requirements to the dev docs.

Add wmic requirement for Desktop App on Windows 11
