mattermost/mattermost-developer-documentation

docs/css/style.css, docs/index.html, site/layouts/index.html, site/layouts/partials/mailinglist.html, site/themes/hugo-elate-theme/static/css/style.css
=> Add mailing list sign-up form

docs/extend/index.html, docs/extend/index.xml, docs/index.html, docs/index.xml, docs/sitemap.xml, site/content/extend/_index.md, site/content/extend/example-plugins.md, site/content/extend/server/_index.md, site/content/extend/server/api-reference.md, site/content/extend/server/hello-world.md, site/content/extend/webapp/_index.md
=> Start "extend" skeleton, basic server hello world

scripts/plugin-godocs.go, site/layouts/shortcodes/plugingodocs.html
To make sure things like section headers format the same.
=> Use go/doc to generate html

site/config.toml, site/content/internal/_index.md, site/content/internal/infrastructure/_index.md, site/content/internal/infrastructure/aws.md, site/content/internal/infrastructure/guidelines.md, site/content/internal/infrastructure/vault.md
Starting by dumping some basic information for some of our recent topics:
http://mattermost-developer-documentation.s3-website-us-east-1.amazonaws.com/branches/internal-docs/internal/
Not linked to from anywhere else on the site at the moment.
I'll add more information over time.
=> Start internal docs

site/content/contribute/redux/_index.md, site/content/contribute/redux/actions.md, site/content/contribute/redux/developer-setup.md, site/content/contribute/redux/developer-workflow.md, site/content/contribute/redux/selectors.md
Not complete by any means but it's a start
=> Start adding some redux docs

site/content/contribute/getting-started/_index.md, site/content/contribute/getting-started/contribution-guidelines.md, site/content/contribute/mobile/_index.md, site/content/contribute/mobile/developer-setup.md, site/content/contribute/redux/_index.md, site/content/contribute/redux/developer-setup.md, site/content/contribute/server/_index.md, site/content/contribute/server/developer-setup.md, site/content/contribute/server/rest-api.md, site/content/contribute/webapp/_index.md, site/content/contribute/webapp/developer-setup.md, site/content/extend/plugins/_index.md, site/layouts/partials/nav.html, site/layouts/partials/nav2.html, site/layouts/shortcodes/contributeurl.html, site/layouts/shortcodes/extendurl.html, site/layouts/shortcodes/integrateurl.html
Removes the broken shortcodes that aren't needed now that relativeUrls = true is set in the config.
Fixes #44.
=> Fix URLs and remove useless shortcodes

site/content/extend/plugins/webapp/_index.md
Once we get some more plugin examples I'd like to add some fancy images, but this is a decent start.
=> Add web app plugin intro

site/content/extend/plugins/server/reference.md, site/layouts/shortcodes/plugingodocs.html
=> Update server reference heading sizes

site/content/extend/plugins/server/hello-world.md
We should probably just make names required.
=> Give server hello world manifest a name

site/content/extend/plugins/server/hello-world.md
It always hurts me a little to have to use ".exe".
=> Update server hello world to work on windows

site/content/extend/plugins/_index.md, site/content/extend/plugins/example-plugins.md, site/content/extend/plugins/manifest-reference.md, site/content/extend/plugins/server/_index.md, site/content/extend/plugins/server/reference.md, site/content/extend/plugins/webapp/_index.md, site/content/extend/plugins/webapp/reference.md
Fixes #51 
I tried to see if Hugo had an easy way to include sections in the tab titles but couldn't find any so I played with some JS a bit but didn't get it to anything I was happy with within a reasonable amount of time
=> Update headings and titles

site/content/contribute/getting-started/respositories.md
We can probably just auto-generate this page but I made some minor updates for now
=> Minor updates to repositories page

site/content/blog/repo-split.md
Related to https://github.com/mattermost/mattermost-server/pull/7892.
=> Makes note of server Makefile changes.

site/content/contribute/devtalks/_index.md, site/content/contribute/getting-started/_index.md, site/content/contribute/mobile/_index.md, site/content/contribute/redux/_index.md, site/content/contribute/server/_index.md, site/content/contribute/webapp/_index.md, site/content/integrate/_index.md, site/themes/content/contribute/_index.md
=> Replace +++ in headers with ---

site/layouts/partials/head.html
Hey guys, adding the bizible script to the head portion of the site on the request of Benoite.
=> Adding bizible script to header

site/content/contribute/redux/_index.md, site/content/contribute/redux/actions.md, site/content/contribute/redux/developer-setup.md, site/content/contribute/redux/developer-workflow.md, site/content/contribute/redux/react-redux.md, site/content/contribute/redux/reducers.md, site/content/contribute/redux/selectors.md
I may have gone a little overboard on this
=> MM-8373 Added Mattermost Redux documentation

site/layouts/partials/sidebar.html
=> Fix expand/collapse buttons for sections with no children

site/content/internal/offboarding.md, site/content/internal/onboarding.md
It should always be assumed that this is missing things. But if you can think of any, let me know and I'll add them.
=> Add internal/offboarding page

site/content/internal/offboarding.md
Looks like I'm still a server admin.
=> Add Discord bullet to offboarding page

site/content/extend/plugins/webapp/reference.md
https://mattermost.atlassian.net/browse/MM-10126 ~~plus some extra documentation of exported libraries~~ and https://mattermost.atlassian.net/browse/MM-10165
=> MM-10126/MM-10165 Document mainMenuActions and exported libraries

site/content/integrate/outgoing-webhooks/_index.md, site/content/integrate/slash-commands/_index.md
This adds a section under integrations re: slash commands.
=> MM-10083: document slash commands

site/static/css/styles.css
Ticket: https://mattermost.atlassian.net/browse/MM-10697
=> MM-10697 - Updating UI for the homepage

site/content/contribute/webapp/build-component.md
Also, all bullet points under "Testing your Component" appear as "1" in the dev site, although they are appropriately numbered in the .md file.
=> Add missing link to contribute/webapp/build-component.md

site/content/internal/infrastructure/vpn.md
I realize this doesn't yet work reliably outside of OSX, but documenting it here for posterity anyway.
=> document how to use the openvpn cli

site/content/contribute/mobile/developer-setup.md
Just some additional steps and information if you want to start developing on Linux. And some things that I had to search a lot of places for to get the right info. I think this could potentially help a lot of people out who want to get started contributing.
Unfortunately i had to 'get rid' of the numbered styling but I think it works like it is now as well. Hadn't had a chance to preview it inside of hugo. But it looks good in markdown preview on github and vscode.
=> Add some linux specific mobile developer setup information 

site/content/internal/infrastructure/vpn.md, site/content/internal/qa/testing_k8s.md
Fixes: https://mattermost.atlassian.net/browse/MM-10358
=> add testing MM on k8s section

site/content/blog/subpath.md
This describes the new subpath feature for developers.
This blog isn't yet "mainstream", but this feels like the right place for a "point in time" description of a feature.
=> blog: subpath

site/content/blog/subpath.md
Realized I had left it as draft: make it public!
=> publish previously authorred subpath blog article

site/content/contribute/redux/actions.md, site/content/contribute/redux/reducers.md
This fixes the [extremely broken](https://user-images.githubusercontent.com/179599/42411330-4eed3532-81fa-11e8-80e1-e367e4eeedb8.png) formatting on the [redux actions page](https://developers.mattermost.com/contribute/redux/actions/).
It also fixes a list that was not properly rendered as a list.
=> Fix code block / list formatting

Makefile, site/content/extend/plugins/_index.md, site/content/extend/plugins/example-plugins.md, site/content/extend/plugins/server/hello-world.md, site/content/extend/plugins/webapp/_index.md, site/content/extend/plugins/webapp/hello-world.md, site/content/extend/plugins/webapp/reference.md, site/layouts/shortcodes/plugingodocs.html
After working through the plugin documentation freshly, a few tweaks were required.
=> clarify plugin docs

site/content/extend/plugins/migration.md, site/content/extend/plugins/webapp/actions.md
https://mattermost.atlassian.net/browse/MM-11517
=> MM-11517 Add plugin documentation for using mattermost-redux actions

site/content/contribute/server/developer-setup.md, site/content/contribute/server/developer-workflow.md
jira: https://mattermost.atlassian.net/browse/MM-11446
=> add doc for make package

site/content/extend/plugins/mobile/_index.md
From this thread https://pre-release.mattermost.com/core/pl/zyqs4bns9f8idbcy486a53gpqr
This question might come up more and more, so it's useful to add this to our developer docs for us to reference.
=> Create a section for mobile plugins

site/content/contribute/server/developer-workflow.md
Documentation for the megacheck make target including some guidance.
CC @jwilander and @jasonblais
=> [MM-11293] Documentation for Megacheck Make Target

site/content/contribute/server/developer-workflow.md
fix https://github.com/mattermost/docs/issues/2153
=> fix: fix command for build web app

site/content/contribute/mobile/build-your-own.md, site/content/contribute/mobile/makefile.md
Updates the environment variables available to build the mobile app as well as the make command to build both apps in sequence
=> Update building the mobile app

site/content/integrate/getting-started/how-should-i-integrate.md
This shouldn't be merged before v5.4 docs are merged, on or a bit before Oct 16th. But we can review ahead of that.
=> Update link for interactive messages

site/layouts/blog/list.html, site/layouts/blog/single.html, site/layouts/blog/summary.html, site/layouts/indexes/category.html, site/layouts/partials/intro.html, site/static/css/styles.css
Working on this for this ticket: https://mattermost.atlassian.net/browse/MM-8374
I've updated the styling of the blog list and single blog pages, along with some other minor global changes.
The subscribe box can be a separate ticket as I would need a dev to plug in the markup for me first and then I can go and style it.
=> MM-8374 - Updating docs styling

site/content/blog/idiomatic-error-handling.md, site/static/css/styles.css
Seeing some confusion around the idiomatic Go tickets and thought this might be a good article to point prospective contributors towards. Plus, it gets us writing more blog articles as we march towards releasing this from beta.
=> blog: idiomatic error handling

site/content/contribute/server/developer-workflow.md
=> Add note about testify in go tests

site/content/internal/infrastructure/_index.md, site/content/internal/infrastructure/aws.md, site/content/internal/infrastructure/build.md, site/content/internal/infrastructure/kubernetes.md, site/content/internal/infrastructure/kubernetes/_index.md, site/content/internal/infrastructure/kubernetes/kubernetes.md, site/content/internal/infrastructure/vault.md, site/content/internal/infrastructure/vpn.md, site/content/internal/offboarding.md, site/content/internal/onboarding.md, site/content/internal/qa/_index.md, site/content/internal/release-process.md, site/content/internal/tips-and-best-practices.md
In draft mode for now to get feedback
=> Add k8s documentation

site/static/css/styles.css
New:
Old:
See https://github.com/mattermost/mattermost-developer-documentation/pull/193#issuecomment-442816263.
=> Reduce size of hanchors

site/content/contribute/server/developer-workflow.md
Follow up on https://github.com/mattermost/mattermost-webapp/pull/2126
=> Remove run-fullmap target

site/content/contribute/mobile/build-your-own.md
Trailing 0 should be removed.
See:
https://github.com/mattermost/mattermost-mobile/pull/2169
https://github.com/wix/react-native-notifications/issues/245
=> Fix doc according to PR-2169

site/content/integrate/slash-commands/_index.md
=> Add note on supported versions for extra_responses parameter in slash commands

site/content/contribute/getting-started/contribution-checklist.md, site/content/contribute/webapp/end-to-end-tests.md
=> [MM-13028] Add E2E documentation for Cypress

site/content/contribute/getting-started/core-committers.md
Added Lev Brouk to the core committers list, thx @hanzei for pointing it out.
=> Added Lev Brouk to core committers

site/content/contribute/mobile/build-your-own.md
Adds a new env var needed when building the iOS app
=> Fastlane env vars

site/content/contribute/redux/actions.md, site/content/contribute/redux/developer-workflow.md, site/content/contribute/redux/selectors.md
This PR update redux unit test location, after we moved unit tests on the same folder of the file being tested.
=> Update redux unit test location

site/content/internal/release-process.md
Adding extra steps that need to be performed after we have a release RC or Final cut.
=> add other steps for release

site/content/contribute/webapp/end-to-end-tests.md
Added at item no. 4.  See screenshot below.
=> Add guideline on how to add test key and description to spec file

site/content/contribute/mobile/developer-setup.md
This goes along with the dep updates and rn 0.58+
=> Update Android Build Tools version

site/content/integrate/slash-commands/_index.md
Please confirm this is correct, based off of https://community.mattermost.com/core/pl/ae4yommjpprippfdm3bwj8moiw
=> Update arguments sent in slash command request

site/content/contribute/server/developer-setup/centos.md, site/content/contribute/server/developer-setup/ubuntu.md, site/content/contribute/server/developer-setup/windows-wsl.md
=> update go ref to 1.12

site/content/contribute/mobile/developer-setup.md
https://developers.mattermost.com/contribute/mobile/developer-setup/ looks a bit wonky due to indentation (image was not shown, list doesn't look like a list)
=> Formatting was a little off on docs

site/content/contribute/webapp/end-to-end-tests.md
Adding a Cypress troubleshooting case on Ubuntu os.
=> Cypress troubleshoot

site/content/contribute/server/developer-setup/windows-wsl.md, site/content/contribute/server/developer-setup/windows.md
the `cd` command at step 8 was missing the `src/github.com/` resulting in an error when using the command
=> fix wrong cd path at step 8

site/content/contribute/getting-started/contribution-checklist.md
See https://github.com/mattermost/mattermost-server/pull/10142 for the discussion about this.
=> Update Contribution Checklist

site/content/extend/plugins/webapp/hello-world.md
Quick change to align with developer standards
=> trivial change: align with developer standards

site/content/contribute/server/_index.md, site/content/contribute/server/developer-workflow.md
Fixes: https://github.com/mattermost/mattermost-developer-documentation/issues/260
=> Fix typo in package name for utils

site/content/contribute/desktop/developer-setup.md
Change to npm install as we don't use yarn anymore
=> Fix install command

site/content/internal/rd-teams.md
Wrote up a quick page detailing who's on which team in R&D
=> Add R&D teams page

site/content/contribute/server/dependencies.md
Documentation to support: https://github.com/mattermost/mattermost-server/pull/10517
=> Dependency management documentation.

site/content/integrate/slash-commands/_index.md
Follow up from https://community.mattermost.com/core/pl/5rpah9eis3yp3gf4qtcemgyswe
=> Add notes how to use bot accounts with slash commands

site/content/internal/infrastructure/vault.md
The document is referring to the old vault address. Updating to cover the change.
=> Updating to the new vault address

site/content/contribute/getting-started/core-committers.md
Adding new QA team member Bob Lubecker to the QA Testers list.
=> Add Bob to QA Testers

site/content/internal/rd-teams.md
Add Eli to platform team, and change Daniel to "Security Eng"
=> Update Platform Team Members.

site/content/internal/rd-teams.md
Added Bob Lubecker to Apps team list as QA.
=> Adding Bob (QA) to Apps team

site/content/contribute/mobile/developer-setup/_index.md
Bumping the minimum version number for Cocoapods since it keeps getting modified whenever I build the mobile app.
=> Update Cocoapods version to 1.6.1

site/content/extend/customization/_index.md, site/content/extend/getting-started/_index.md
See https://community-release.mattermost.com/core/pl/hmciwrmn3i835cf5wdb199s5ga for details, fixing a few more along the way.
The /extend section of this site generally seems in need of an overhaul.  This is just a bandage for now.
=> Fix various links

site/content/extend/plugins/server/best-practices.md
This is to cover docs for https://github.com/mattermost/mattermost-server/pull/10476
=> Starting server plugin best practice doc

site/content/contribute/webapp/developer-setup.md
Going to mark WIP until https://github.com/mattermost/mattermost-developer-documentation/pull/309 is merged
=> Fix step numbers and fix code formatting in webapp/developer-setup

site/content/extend/plugins/community_process.md
Draft proposal for process to get plugins onto community.
=> MM-16268 Community plugin process.

site/content/contribute/desktop/code-signing.md, site/content/contribute/desktop/developer-setup.md, site/content/contribute/getting-started/labels.md, site/content/extend/getting-started/_index.md, site/content/internal/offboarding.md, site/content/internal/sustained-engineering.md
I fixed several small typos I found while reading the documentation. ✅ 🙂
=> Small typos fixed in the documentation.

site/content/contribute/redux/reducers.md
removed unnecessary "we" in sentence.
=> Remove unnecessary word in sentence.

site/content/contribute/getting-started/core-committers.md
Credit to @lindalumitchell for putting this all together: I'm just submitting the PR :)
=> Updated QA testers

site/content/contribute/getting-started/inactive-contributions.md, site/layouts/shortcodes/note.html, site/static/css/note.css
Applied the note shortcode: https://github.com/mattermost/mattermost-developer-documentation/tree/master/site/layouts/shortcodes
to the content for better format.
=> Applied the note shortcode to the notes

site/content/contribute/server/developer-workflow.md
Based on [this discussion](https://community.mattermost.com/core/pl/34yg85h8ujfhjbf1rr8j67snrh) :)
=> Add alternatives to `make-test`, which can take some time

site/content/blog/2018-07-18-plugins-v2.md, site/content/contribute/getting-started/core-committers.md, site/content/extend/embed/_index.md, site/content/extend/plugins/_index.md, site/content/integrate/getting-started/_index.md, site/content/internal/onboarding/new-staff-guide.md, site/content/internal/rd-teams.md
Updating the various lists on mattermost.dev. Let me know if the updated dev areas make sense!
=> add Shota & Ben as Staff

site/content/contribute/getting-started/labels.md, site/content/contribute/webapp/end-to-end-tests.md
Inputs from - https://github.com/mattermost/mattermost-server/issues/9805#issuecomment-528063746
Screenshot (updated per latest comment):
=> Update docs of test key in writing E2E

site/content/internal/onboarding/manager-guide.md, site/content/internal/onboarding/new-staff-guide.md, site/content/internal/rd-teams.md
- Added steps to on-boarding guides.
- Added a few new missing hires to list of R&D folks.
=> Update on-boarding guides

scripts/plugin-godocs.go, site/layouts/shortcodes/plugingodocs.html
Add automatic helpers section for plugin.
Fixes https://github.com/mattermost/mattermost-server/issues/12264
=> add plugin helpers section

site/content/extend/plugins/community_process.md
When we were going through the plugin process (Christopher, Lev and I) we thought these might be some easy fixes to make the process a bit clearer for external folks.
Completely open to suggestions/rewording/improvements.
=> Quick fixes to the plugin process docs

site/content/contribute/mobile/_index.md
Javascript text was linking to golang website.
=> Fixed Javascript Link

site/content/contribute/mobile/developer-setup/_index.md
Bump Cocoapods required version
=> Update Cocoapods to 1.7.5

site/content/contribute/mvp/_index.md
=> Update MVP Page

site/content/contribute/server/rest-api.md
Fixes https://github.com/mattermost/mattermost-developer-documentation/issues/401
=> Updated the URLs

site/content/contribute/getting-started/_index.md
Help wanted issues no longer exist in server repository only. Modify the description to reflect that.
=> Modify step 4 description for help wanted issues

site/content/contribute/getting-started/labels.md
Follow up on https://community.mattermost.com/core/pl/1846u5i37pfsx8ytex4jefiqqy
=> Add UX review labels

site/content/contribute/getting-started/labels.md, site/content/contribute/getting-started/slash-commands.md
=> Add update branch automerge

site/content/internal/rd-teams.md
Interim updates for QA staff info (will update further as more team members join and team assignments settle in more).
=> Update QA staff info

site/content/extend/plugins/signing-plugins.md
This PR will document the process for signing a plugin bundle and deploying the public key with the Mattermost server to verify the signature.
=> [MM-16585] Document signing plugins

site/content/contribute/getting-started/core-committers.md, site/content/internal/rd-teams.md
Add Ian Tao to Toolkit and as a PM.
=> add Ian Tao

site/content/contribute/mobile/build-your-own/environment-vars.md
Corresponds to changes in https://github.com/mattermost/mattermost-mobile/pull/3767
=> Additional env variable in mobile repo

site/content/blog/2019-12-18-cloud-monitoring.md
=> MM-2001-2 Removing a gap to test github actions

site/content/internal/rd-teams.md
See areas of responsibility for tech writers: https://handbook.mattermost.com/operations/research-and-development/product/product-technical-writing-team-handbook#areas-of-responsibility
=> Move Justine from "Other" to the relevant R&D teams

site/content/internal/rd-teams.md
Updated the Security team section of the handbook.
=> Update Security Team Entries

site/content/blog/2020-01-13-incorporating-golangci-lint.md
Fix md formating
Follow up on https://github.com/mattermost/mattermost-developer-documentation/pull/483
=> Fix md formating for golangci-lint post

site/content/integrate/slash-commands/_index.md
Accompanying doc change to https://github.com/mattermost/mattermost-server/pull/13320
=> Add information on ``skip_slack_parsing``

site/content/internal/sustained-engineering.md
Formalizing how to engage SET for customer support requests
=> Formalizing customer support tickets process with SET

site/content/contribute/webapp/developer-setup.md
In #387, we removed the instructions for placing your code in the GOPATH, but it looks like we missed the webapp instructions.  This just cleans those up to match.
None.
=> Updated the webapp developer docs to match #387

site/content/integrate/slash-commands/_index.md
- Correct what the endpoint request would look like for the slash command example.
- N/A
=> correct endpoint request in slash command docs

site/content/contribute/server/developer-setup.md
I have added minimum software requirements to successfully deploy a developer environment.
Fixes https://github.com/mattermost/mattermost-developer-documentation/issues/528
https://community.mattermost.com/core/pl/aexmr4p7x7n79mwg4gnezp9h6r
=> Added minimum SW requirements to developer-setup

site/content/internal/rd-teams.md
Also updated core-committers.md (https://github.com/mattermost/mattermost-developer-documentation/pull/535)
=> Added Nevy

site/content/internal/infrastructure/vpn-cloud.md
Updating the how to connect to VPN documentation
=> update how to connect vpn documentation

cmd/plugin-godocs/plugin-godocs.go, site/layouts/shortcodes/plugingodocs.html
Fix variadic functions being shown as `[]`. I also did some cleanup of the code to keep it DRY.
https://mattermost.atlassian.net/browse/MM-22700
=> [MM-22700] Fix variadic functions on the plugin docs page

site/content/contribute/desktop/developer-setup.md
On windows we are using a powershell script to manage most of the commands in an unified way. This documentation gives some info on how to use it and some problems people might find
=> Documentation about makefile

site/content/contribute/webapp/end-to-end-tests.md
Add guide to add check for Cypress test that requires license
none
=> Add guide to add check for Cypress test that requires license

Makefile
This is needed because e.g. https://github.com/mattermost/mattermost-developer-documentation/pull/558 use a future date to ensure that the blog does't get posted yet.
=> Also build future posts in dev environment

site/content/contribute/containers/_index.md
As part of increasing awareness and make things more clear, this PR adds some documentation regarding all containers we have at Mattermost and try to describe where we use
Also updated the docker hub description for each (or almost all) repositories.
JIRA: https://mattermost.atlassian.net/browse/MM-22990
=> Add new section to describe all containers we have at Mattermost

.github/workflows/notify-mm-blog.yml
There is an issue with quoting. This should fix it. 
Fixes https://github.com/mattermost/mattermost-developer-documentation/issues/518
=> Fix quoting issue

site/content/extend/plugins/best-practices.md
Extended documentation on how to define a plugins configuration settings. I've included as a previous question to the custom setting in Extend/Plugins/Best Practices
[MM-21364](https://mattermost.atlassian.net/browse/MM-21364)
=> MM-21364 - Plugin Settings Config Best Practices

.github/workflows/notify-mm-blog.sh, .github/workflows/notify-mm-blog.yml
Fixes quoting issue. 
https://mattermost.atlassian.net/browse/IS-368
https://github.com/mattermost/mattermost-developer-documentation/issues/518
=> IS-368: Fix blog quoting issue.

site/content/internal/onboarding/new-staff-guide.md
Redshift Analytics has been replaced with Snowflake. I've removed the mention to Redshift in the _Potential topics to chat with a daily mentor about_ list and made the item more generic: the specific product is not that important, while the strategy is.
=> Remove mention to unused technology

site/content/internal/infrastructure/grafana.md
Adding documentation on how to create dashboards and panels for community servers.
=> MM-23182 Adding documentation for community Grafana dashboards

site/content/contribute/getting-started/slash-commands.md
Docs update for https://github.com/mattermost/mattermost-mattermod/pull/92
=> Allow submitter of a PR to user /update-branch

site/content/contribute/server/developer-setup.md
Bump minimum required Go version to 1.14
=> Bump up minimum required Go version

site/content/contribute/getting-started/core-committers.md, site/content/internal/rd-teams.md
=> Add Caleb to Apps team

site/content/contribute/containers/_index.md
Add a description for matterwick and chewbacca images
=> add information about the chewbacca image

site/content/internal/rd-teams.md
Adding myself as a designer in the workflow team
=> Adding myself as a designer in the workflow team

site/content/contribute/mobile/push-notifications/service.md
Adds documentation on how to use a proxy server for push proxy
https://mattermost.atlassian.net/browse/MM-23891
=> Add documentation on proxy support

site/content/blog/2020-05-20-hands-on-iouring-go.md
Right now, it gives the impression that the post gets hands-on with Go also. We fix that.
=> Change title of iouring blog post

site/content/extend/plugins/webapp/reference.md
Documented CSS variables for theme colors
https://github.com/mattermost/mattermost-developer-documentation/issues/630
=> #GH-630 documented CSS variables for theme colors

site/content/contribute/getting-started/core-committers.md
Adds documentation for #624.
We can add more details on steps 6 and 7 once we've done these for Andre.
=> Add core committer process

site/content/internal/sustained-engineering.md
Changed the intro to be accurate again.
=> Update SET doc to match newest rotatiaon process

site/content/internal/rd-teams.md
=> Update Apps Team members

site/content/contribute/getting-started/core-committers.md
I should have asked for editor review on https://github.com/mattermost/mattermost-developer-documentation/pull/653 :)
=> Fix formatting of new core committer

.github/workflows/gh-pages.yml, README.md
Fix bug that was only deploying the latest PR
=> Gh pages bug

site/content/contribute/getting-started/core-committers.md
Waiting for one final permission, submitting a PR for review so we're ready to merge and announce :tada:
=> WIP: Promote @rvillablanca as a core committer

site/content/contribute/webapp/end-to-end-tests.md
=> E2e docs storybook

site/content/contribute/mobile/e2e/_index.md, site/content/contribute/mobile/e2e/android.md, site/content/contribute/mobile/e2e/file-structure.md, site/content/contribute/mobile/e2e/guide-for-writing.md, site/content/contribute/mobile/e2e/ios.md
- Add mobile E2E documentation
NA
=> MM-28649 Add Mobile E2E documentation

site/content/contribute/mobile/build-your-own/preparation.md
update to fix typo and mention no cask needed for fastlane
=> typo and instructions

.github/workflows/gh-pages.yml
=> Env var update

.github/workflows/gh-pages.yml
=> Update if conditional logic

site/content/contribute/mobile/e2e/guide-for-writing.md
- Added a new item for comment indicator guide.
NA
=> Add comment indicator guide

site/content/contribute/webapp/using-i18n-extract.md
Fix image path for https://developers.mattermost.com/contribute/webapp/using-i18n-extract/
None
=> Fix image path for make i18n-extract docs

site/content/blog/2020-10-28-docker-content-trust-in-gitlab-with-delegation.md
=> 2020-10-28-docker-content-trust-in-gitlab-with-delegation

site/content/contribute/redux/actions.md, site/content/contribute/redux/react-redux.md, site/content/integrate/outgoing-webhooks/_index.md, site/content/integrate/slash-commands/_index.md
Fix some code blocks that language isn't specified. And fix missing comma and indentation.
N/A
=> Specify required language in code blocks

site/config.toml, site/layouts/partials/footer.html, site/layouts/partials/head.html, site/static/robots.txt
This pull request includes configuration changes and modifications to the global header and footer files based on requests for SEO optimizations. The configuration file for the site has been modified to use absolute URLs for links, sitemap, canonical meta tag, and app assets like css and javascript files.
- config.toml updated to use absolute URLs, affects page links, meta tags, script and css references, and sitemap.xml
- head.html revised to better leverage absolute url paths, scripts moved to footer.html
- footer.html app javascript references moved from head.html to reduce render blocking scripts on page load
- robots.txt added per specification provided by SEO team
https://mattermost.atlassian.net/browse/MAR-158
https://mattermost.atlassian.net/browse/MAR-163 …
=> SEO Updates for canonical URLs, robots.txt, moved app scripts to footer

site/layouts/partials/footer.html, site/static/css/styles.css
This PR updates the footer buttons to include transitions to match other website elements such as the buttons on the index page.
=> Update footer button transitions to match other website elements

site/content/blog/2020-03-17-maintaining-consistency-in-codebases-with-go-vet.md, site/content/blog/2020-05-04-pritunl.md, site/content/blog/2020-06-10-opentracing.md, site/content/blog/2020-07-27-automated-ui-testing-with-cypress.md, site/content/blog/2020-09-07-improving-performance-through-load-testing.md, site/content/blog/2020-10-28-docker-content-trust-in-gitlab-with-delegation.md
The SEO team has requested that the pages included in this pull request be updated with new canonical URLs.
See comments from Vance in this ticket:
https://mattermost.atlassian.net/browse/MAR-179
=> Canonical URL corrections per SEO team

site/content/extend/plugins/developer-workflow.md
Added description for `make clean` command
=> Minor update for developer-workflow.md

site/content/internal/infrastructure/onelogin-aws.md
Update the AWS credential instructions to point to the correct documentation.
=> Update AWS Credential Generation Instructions

site/content/contribute/mobile/storybook.md
- Add docs about storybook react native to our developer docs
- https://mattermost.atlassian.net/browse/MM-32864
=> [MM-32864] Add docs about storybook react native

site/content/contribute/server/feature-flags.md
Documenting feature flags Q&A for easier reference. Let me know if any other common Q&A should be added.
=> Adding feature flags Q&A

site/content/contribute/server/style-guide.md
Add application structure guidelines
This is something which I feel needs to be mentioned and should be helpful. A lot of repos are being created, each with the developer's own taste. Some amount of unification will be helpful.
I have refrained from being too preachy. Just kept it to basic common sense and some anti-patterns to avoid. Rest is up to the developer.
=> Add application structure guidelines

site/content/contribute/server/feature-flags.md
Add basic instructions on how to use Split for feature flags.
=> Add basic instructions on how to use Split for feature flags

site/content/extend/plugins/webapp/hello-world.md
=> Add info about enabling plugin during manual installation

site/content/integrate/apps/_index.md, site/content/integrate/examples/_index.md, site/content/integrate/getting-started/_index.md, site/content/integrate/incoming-webhooks/_index.md, site/content/integrate/outgoing-webhooks/_index.md, site/content/integrate/rest-api/_index.md, site/content/integrate/slash-commands/_index.md
This _might_ fix an issue with the Apps docs not getting listed in the LHS. Never the less it's a good addition.
None
=> Add weight to integrate docs

site/content/integrate/apps/bindings/_index.md, site/content/integrate/apps/call/_index.md, site/content/integrate/apps/interactivity/_index.md, site/content/integrate/apps/interactivity/example-post-menu/_index.md, site/content/integrate/apps/lifecycle/_index.md, site/content/integrate/apps/manifest/_index.md, site/content/integrate/apps/quick-start-go/_index.md, site/content/integrate/apps/using-mattermost-api/_index.md, site/content/integrate/apps/using-third-party-api/_index.md
Fix unfolding of the LHS menu
None
=> Fix LHS menu

site/content/integrate/apps/quick-start-js/_index.md
- hello-world > helloworld
- Added uninstall step
=> JS quickstart: formatting and new step

site/content/integrate/apps/_index.md
=> Update index: Link to go driver

site/content/integrate/apps/call/_index.md
This PR fixes a small spelling error.
n/a
=> Fix small spelling error

site/content/blog/2021-04-19-nodes-automation-image.md
=> fix typos in blog post

site/content/contribute/mobile/build-your-own/android.md
Remove weird an unnecessary `\` on the environment variable names
=> Update android env vars

site/content/contribute/server/style-guide.md
The developers document is a more prominent place
where lots of contributors hit.
We copy some of the material from the doc to improve
visibilty and point to the rest of the doc.
=> Cross-link the perf review document

site/content/contribute/mobile/developer-setup/_index.md
Updates doc to reflect that node 16 and npm 7 is required for mobile
=> Mobile app to use node 16 and npm 7

site/content/internal/infrastructure/vpn-cloud.md
Update VPN documentation with configuration regarding local DNS resolution
=> update vpn documentation for MacOS resolv.conf

site/content/integrate/admin-guide/admin-bot-accounts/_index.md
I updated the Bot Account Creation and  User Interface section to add instructions on adding the bot account to a Team, and also took the liberty of adding information on saving the bot account key as I felt that was missing as well.
I wasn't really sure the best place to put the team add info, so I just added it on to an existing sentence rather than create its own section because it seemed simple enough that it didn't need its own space. If you want it to have its own section though I could certainly do that.
https://github.com/mattermost/docs/issues/3859
=> update bot account creation and UI sections

site/content/integrate/admin-guide/admin-webhooks-incoming/_index.md
Fixes https://github.com/mattermost/docs/pull/4901
=> Updated Depreciated Links in admin-webhooks-incoming _index.md

site/content/integrate/admin-guide/admin-webhooks-outgoing/_index.md
=> Updated broken links in admin-webhooks-outgoing _index.md

site/content/integrate/apps/_index.md
remove reference to self-deployed customers coming later.
=> remove reference to "available in future" line

site/content/integrate/admin-guide/admin-bot-accounts/_index.md
=> updated broken links in admin-bot-accounts _index.md

site/content/integrate/admin-guide/admin-slash-commands/_index.md
Updated deprecated links in the admin-slash-commands  _index.md
NA
=> Updated deprecated links in admin-slash-commands _index.md

site/content/integrate/slash-commands/_index.md
=> Update _index.md / Slash Commands

site/content/contribute/desktop/_index.md
The deprecated links were updated and the raw links were formatted for a better look and feel.
NA
=> Updated contribute/desktop _index.md

site/content/integrate/admin-guide/admin-interactive-messages/_index.md
Updated the deprecated link in admin-interactive-messages _index.md
NA
=> Updated the deprecated link in admin-interactive-messages _index.md

site/content/extend/getting-started/_index.md
Fixed broken links and updated the links
=> Update _index.md / Plugins

site/content/contribute/containers/_index.md
The links were directly written onto the page which was not looking nice. Proper formatting has been provided for the links.
NA
=> Updated contribute/containers _index.md

site/content/integrate/admin-guide/_index.md
I updated the developer guides landing page to be more informative and provide basic descriptions of the major content in that section with relevant hyperlinks.
None
Note: I'm also using this commit as a way to rerun the GitHub Actions for this repo because we've had some issues after their service outage yesterday.
=> Update Content in Developer Guide.

site/config.toml
3rd time is the charm? :-) This PR should fix the missing Integrate & Extend top nav item.
None.
=> Fix Integrate & Extend Top Nav

site/content/integrate/apps/call/_index.md
Add localization documentation
https://github.com/mattermost/mattermost-plugin-apps/pull/227#pullrequestreview-737191929
=> Add localization documentation

site/content/integrate/apps/interactivity/_index.md
Add information about open in form functionality. See the related PRs for more context.
https://github.com/mattermost/mattermost-webapp/pull/8597
Mobile: TBD
=> Add information about open in form

site/content/integrate/admin-guide/admin-plugins-beta/_index.md, site/content/integrate/plugins/_index.md
=> Rename plugins docs (duplicated) and general editing

site/content/integrate/plugins/_index.md
=> Remove references to Beta

site/content/integrate/plugins/community-plugin-marketplace.md
Remove reference to plugins in Beta
=> Remove reference to Beta

site/content/contribute/webapp/developer-setup.md
Added instruction for installing node via nvm
As per recommendation from https://github.com/mattermost/mattermost-webapp/pull/9335#issuecomment-966427513
=> Instruction to install node via nvm

site/static/scripts/sign-android
Modified the `sign-android` script to form the `FIREBASE_URL` property from the `PROJECT_ID`.
=> Modified to create FIREBASE_URL

site/content/integrate/admin-guide/admin-interactive-messages/_index.md
Fixes https://github.com/mattermost/docs/issues/1883
=> Clarify http response in interactive message docs

site/content/contribute/gsoc/_index.md
Updating Google Summer of Code guide for 2022
n/a
=> Update Gsoc Guide for 2022

site/content/contribute/getting-started/labels.md
Fix #618 
Setup Cloud Test Server label triggers the creation of an Enterprise Edition test server and not just Test Server
=> [Docs]: Updating Label

site/content/contribute/server/feature-flags.md
Add details on how to request access to Split.
=> Update feature flags doc

site/content/contribute/server/developer-setup/arch.md, site/content/contribute/server/developer-setup/centos.md, site/content/contribute/server/developer-setup/osx.md, site/content/contribute/server/developer-setup/ubuntu.md, site/content/contribute/server/developer-setup/windows-wsl.md
This is not necessary anymore. GOBIN is now automatically set from
the Makefile.
=> Remove mention of GOPATH

site/content/contribute/server/dependencies.md
I removed the make update-dependencies because it's complicated
to make it work for a contributor.
=> Update dependencies page

site/content/contribute/getting-started/inactive-contributions.md
A bot now adds the stale label so updated the docs to reflect that.
=> Minor updates to the inactive contributions process

site/content/contribute/mobile/e2e/guide-for-writing.md, site/content/contribute/webapp/e2e/guide-for-writing.md
Updated instructions for `If test case is failing due to Known Issue` in webapp and mobile e2e guides
=> updated e2e guide for writing

site/content/contribute/getting-started/contribution-checklist.md, site/content/contribute/getting-started/inactive-contributions.md, site/content/contribute/getting-started/labels.md, site/content/contribute/getting-started/test-guideline.md, site/content/contribute/getting-started/test-policy.md, site/content/contribute/getting-started/test-servers.md
Initially prepared in this document - https://docs.google.com/document/d/1OPzjYg3EPuNaXS4Hjyht_18UqZsfSAsEtGjMDpsNl8w/edit#
This document was written to stress the importance of tests for every pull request being submitted. This is not to meet higher code coverage but rather to write effective and well-planned use cases depending on the changes being made.
This document aims to serve as the foundation of our test guideline, and serves as a reference on why we don't merge code without tests. But of course, there's always an exception. Please read through the docs for more details.
Note that tracking of PRs with test is not discussed in this PR. 
I've added bunch of reviewers but feel free to add/transfer review and/or chime-in (for anyone reading this PR).
=> Add test guideline when contributing code

site/content/integrate/admin-guide/admin-plugins-beta/_index.md
Mention that remoteMarketplaceURL also gets disabled when enableUploads is disabled.
https://mattermost.atlassian.net/browse/MM-41323
=> Add remoteMarketplace changes

site/content/contribute/server/developer-workflow.md
Add make store-mocks and make store-layers to the server workflow.
Fixes https://github.com/mattermost/mattermost-developer-documentation/issues/362
=> Add make store-mocks and make store-layers to the server workflow

site/content/contribute/server/developer-workflow.md
Document `MM_NO_DOCKER` environment variable.
Fixes https://github.com/mattermost/mattermost-developer-documentation/issues/404
=> Add note about MM_NO_DOCKER env var

site/content/contribute/server/schema-migration-guide.md
Adds new `make migrations-extract` process to the schema migration guide.
=> contribute/schema-migration-guide: add new make migrations-extract proc.

.github/workflows/check-label.yml, .github/workflows/preview-env-fork.yml, .github/workflows/preview-env.yml
Simplify pipeline code by moving common step conditions to job level.
=> Move common check conditions to job level

site/content/contribute/webapp/e2e/folder-and-file-structure.md, site/content/contribute/webapp/e2e/guide-for-writing.md, site/content/contribute/webapp/e2e/running-e2e.md
Update folder structure of Cypress in mattermost-webapp. This does not include Playwright yet as I'm going to submit it separately.
none but mentioned here - https://github.com/mattermost/mattermost-developer-documentation/issues/1086
=> Update folder structure of Cypress in mattermost-webapp

site/content/contribute/mobile/developer-setup/_index.md
Added an Environment Troubleshooting section and included steps to address a particularly painful issue I had to work through to get `ios` packages to build.
=> troubleshooting section for nvm

site/content/contribute/getting-started/contributions-without-ticket.md
Based on [feedback](https://community.mattermost.com/core/pl/iksk5hhdrtd48j1pnzcjpw18fw) proposing to add a hint where translation should be fixed.
=> Add where to fix translation

site/content/contribute/more-info/desktop/developer-setup/macos.md
Add instructions for Macs with M1 chips
=> Update macos.md - M1 arch

site/content/contribute/more-info/webapp/e2e-cheatsheet/basic-code-structure.md
=> Remove storybook references

site/layouts/_default/list.html, site/layouts/_default/single.html, site/layouts/partials/sidebar-v2-recurse.html, site/layouts/partials/sidebar-v2.html
This PR adds support for recursive sidebar rendering, enabling the entire document hierarchy to be seen.
The original sidebar template was left as-is for troubleshooting and reference.
=> Recursive sidebar menu

site/content/contribute/more-info/server/developer-setup/arch.md, site/content/contribute/more-info/server/developer-setup/centos.md, site/content/contribute/more-info/server/developer-setup/osx.md, site/content/contribute/more-info/server/developer-setup/ubuntu.md, site/content/contribute/more-info/server/developer-setup/windows-wsl.md
- Fixed also bad ticket number
=> Fixed several broken links for developer setup

site/content/contribute/more-info/mvp/_index.md
=> MVP 7.5 updated

site/content/contribute/more-info/getting-started/branching.md
So today I had to do a manual cherry-pick, and I was thinking let's follow our doc, and realized we don't have one for this! So, I decided to write it in parallel to doing it on my computer.
N/A
=> add instructions for manual cherry pick

site/content/integrate/customization/customization/webapp.md
Most of these steps duplicates https://docs.mattermost.com/configure/customizing-mattermost.html#mattermost-web-app. I don't think that's ideal, but at least they're up to date now.
https://mattermost.atlassian.net/browse/MM-49021
=> MM-49021 Update web app customization steps to account for products

site/static/css/bar.css, site/static/css/styles.css
A followup to  PR https://github.com/mattermost/mattermost-developer-documentation/pull/1198 – found some mobile styles that needed to be adjusted, specifically for the notification bar and search inputs (text-wrapping, width, etc. ).
Lemme know, if anything – TY~
=> Mobile style updates

site/config.toml, site/content/integrate/apps/functionality/oauth2.md
This PR updates the notification banner with the upcoming Gitlab webinar details
Let me know if there's any questions, thanks!
=> Update notification bar copy

site/config.toml, site/layouts/partials/notification.html, site/static/css/bar.css, site/static/css/styles.css, site/static/js/main.js
This PR updates the notification banner for the MM/MST LP.
As discussed, the targeted merge for this PR is tomorrow, Mar 9th @ 9am EST.
cc: @cwarnermm @azigler @nat-gunner for visibility - adding everyone as a reviewer for more coverage
TY!
=> Update notification banner

.github/workflows/preview-env.yml
[chore] preview pipeline test after building the docs
Local testing: 
```
❯ hugo -F -s site --baseURL http://mattermost-dev-docs-preview-pulls.s3-website-us-east-1.amazonaws.com/1227/ --destination ../dist/html                                                                 ✘ 255
Start building sites …
hugo v0.111.3+extended darwin/arm64 BuildDate=unknown
| EN
-------------------+------
Pages            | 375
Paginator pages  |   3
Non-page files   | 207
Static files     | 162
Processed images |   0
Aliases          | 189
Sitemaps         |   1
Cleaned          |   0
Total in 292 ms
❯ make test
npm install
up to date, audited 51 packages in 479ms
6 packages are looking for funding
run `npm fund` for details
found 0 vulnerabilities
npm notice
npm notice New major version of npm available! …
```
=> [chore] preview pipeline test after building the docs

site/content/contribute/why-contribute/_index.md
Documentation for: https://github.com/mattermost/mattermost-handbook/pull/1202
=> Added Handbook link

site/content/integrate/apps/structure/bindings/_index.md, site/content/integrate/apps/structure/call/_index.md, site/content/integrate/apps/structure/manifest/_index.md
This PR addresses https://github.com/mattermost/mattermost-developer-documentation/issues/1229
=> Added redirects

site/content/integrate/plugins/overview.md
Currently it points to `.js` file. Although it seems, the js file has been updated to `.ts` file.
=> Update plugin shell github link in overview.md

site/content/integrate/plugins/using-and-managing-plugins.md
This pull request updates the "Using and Managing Plugins" documentation in the Mattermost official documentation. It improves the instructions for enabling plugin uploads in Mattermost Omnibus installations.
=> Adding instructions for enabling plugin uploads in Mattermost Omnibus installation

site/content/contribute/developer-setup.md
Fixes https://mattermost.atlassian.net/browse/MM-53925
Fixes https://github.com/mattermost/mattermost/issues/24120
Fixes https://github.com/mattermost/mattermost-developer-documentation/issues/1282
=> Added instruction to install rosetta on ARM macs for libpng to work

site/content/contribute/developer-setup.md
Small clarification added to developer setup docs.
NONE
=> Specify which directory to be in when running `nvm install`

site/layouts/partials/footer.html, site/static/css/styles.css
This PR updates the Twitter/X logo in the footer. TY!
=> Update Twitter logo in footer

site/config.toml
This PR updates the notification banner with the Hacktoberfest announce 🍂 TY!
=> Update the notification banner for Hacktoberfest

.github/workflows/check-label.yml
Rationale: https://mattermost.atlassian.net/browse/CLD-5750
=> [fix] CI, fixing check-label-preview IF clause Scope

site/content/contribute/developer-setup.md
Reorder setup the Mattermost Server bullet points:   
It makes more sense to have the folder already available when documentation mention running the command within the webapp/ folder
=> Reorder setup the Mattermost Server bullet points

site/content/contribute/more-info/getting-started/contribution-checklist.md
This PR adds an extra note for Ticket assignment to contributors.
Fixes #959
=> Ticket Assignment Update Note

site/content/contribute/more-info/server/style-guide.md
Document the style guidelines around annotated logging in the server
None
=> Add annotated logging to style guide

site/config.toml, site/layouts/partials/nav.html, site/layouts/partials/nav2.html, site/static/css/styles.css
This PR updates the nav to match the new structure on mm.com, and slots in the webinar promo in the notification banner.
https://app.asana.com/0/1201867728201087/1206694960394434/f
=> Update nav structure and notification banner content

site/content/contribute/more-info/server/feature-flags.md
Removes references to Split.io as we move off of it next week. Adds some basic instructions for altering feature flag values using the environment variable scheme. 
N/A
=> Adjust documentation around feature flags to remove references to split.io

site/config.toml
This PR updates the notification bar with a CTA for the upcoming copilot webinar.
=> Update notification bar with Copilot webinar CTA

site/content/contribute/more-info/mobile/developer-setup/_index.md
Per discussion here: https://community.mattermost.com/core/pl/3atndp1nb3g77y5mtux9ekmnfa
=> Update mobile dev setup to reflect requiring ruby 3.0.6

site/content/contribute/more-info/mobile/developer-setup/_index.md
Update node to v20 and npm to v10
=> update node to v20 and npm to v10

site/content/integrate/reference/bot-accounts/_index.md
Based on customer feedback via @jlandells
=> Clarified that bot accounts can't be used to upload files to a channel

site/config.toml
This PR updates the notification banner with a callout to the v10 Release Blog.
n/a
=> Update notification banner for Sept v10 launch

site/config.toml
This PR updates the notification banner with the Hacktoberfest announce that links to the mm.com LP.
=> Update notification banner for Hacktoberfest announce

.github/workflows/preview-env-fork.yml, .github/workflows/preview-env-template.yml, .github/workflows/preview-env.yml
Use the same foolproof mechanism we use on https://github.com/mattermost/docs repository to handle fork builds
=> feat: Upgrade the way we deploy preview environments from forks

site/content/contribute/more-info/webapp/_index.md, site/content/contribute/more-info/webapp/redux/_index.md
Corrected the spelling of the word "application" in two places.
I mentioned it first in the [documentation channel](https://community.mattermost.com/core/pl/8uqjnprt8bgkjgb71khxwcrnsw).
N/A
=> Correct "application" spelling

site/content/contribute/developer-setup/_index.md
Documentation for: https://github.com/mattermost/mattermost-developer-documentation/issues/1421
=> Added note re: webapp port

site/content/contribute/more-info/server/tests.md
As discussed in the developers' meeting, the process for handling flaky tests was not documented. This PR changes that.
https://community.mattermost.com/core/pl/hrbrcoupipdt98kz4nqi1poxow
=> Document process for flaky server tests

site/content/contribute/more-info/mobile/developer-setup/_index.md
Update node version to 22 since mattermost-mobile will use v22 (see this https://github.com/mattermost/mattermost-mobile/pull/8657)
=> docs: Update node to v22

site/content/contribute/developer-setup/_index.md
https://mattermost.atlassian.net/browse/MM-62928?
=> Add instructions to build and deploy Mattermost

site/content/contribute/more-info/server/style-guide.md
I have been working with @hanzei to improve some of our error logging guidelines. We are starting out small, but the aim is to keep improving this if there are new stuff to be added.
Overall, these points in the PR are something that I have seen multiple times in multiple PRs. So I think there's value in capturing these in the style guide so that it can be referred in PR reviews.
=> Improve error logging guidelines

site/content/contribute/developer-setup/_index.md
Updates from my experience setting up development for the mattermost repo.
None
=> Corrections for setting up development environment for mattermost repo
